//
//  ACFramework.h
//  ACFramework
//
//  Copyright © 2017 Microsoft. All rights reserved.
//

#import <UIKit/UIKit.h>

//! Project version number for ACFramework.
FOUNDATION_EXPORT double AdaptiveCardsFrameworkVersionNumber;

//! Project version string for AFramework.
FOUNDATION_EXPORT const unsigned char AdaptiveCarsFrameworkVersionString[];
#ifdef SWIFT_PACKAGE
/// Swift Package Imports
#import "ACOActionOverflow.h"
#import "ACOAdaptiveCard.h"
#import "ACOAdaptiveCardParseResult.h"
#import "ACOBaseActionElement.h"
#import "ACOBaseCardElement.h"
#import "ACOEnums.h"
#import "ACOHostConfig.h"
#import "ACOHostConfigParseResult.h"
#import "ACOIResourceResolver.h"
#import "ACOInputResults.h"
#import "ACOMediaEvent.h"
#import "ACORemoteResourceInformation.h"
#import "ACORenderContext.h"
#import "ACOResourceResolvers.h"
#import "ACRActionDelegate.h"
#import "ACRActionOpenURLRenderer.h"
#import "ACRActionSetRenderer.h"
#import "ACRActionShowCardRenderer.h"
#import "ACRActionSubmitRenderer.h"
#import "ACRAggregateTarget.h"
#import "ACRBaseActionElementRenderer.h"
#import "ACRBaseCardElementRenderer.h"
#import "ACRBaseTarget.h"
#import "ACRButton.h"
#import "ACRChoiceSetCompactStyleView.h"
#import "ACRColumnRenderer.h"
#import "ACRColumnSetRenderer.h"
#import "ACRContainerRenderer.h"
#import "ACRContentHoldingUIView.h"
#import "ACRErrors.h"
#import "ACRFactSetRenderer.h"
#import "ACRIBaseActionElementRenderer.h"
#import "ACRIBaseCardElementRenderer.h"
#import "ACRIBaseInputHandler.h"
#import "ACRIMedia.h"
#import "ACRImageProperties.h"
#import "ACRImageRenderer.h"
#import "ACRImageSetRenderer.h"
#import "ACRInputChoiceSetRenderer.h"
#import "ACRInputDateRenderer.h"
#import "ACRInputLabelView.h"
#import "ACRInputNumberRenderer.h"
#import "ACRInputRenderer.h"
#import "ACRInputTimeRenderer.h"
#import "ACRInputToggleRenderer.h"
#import "ACRMediaRenderer.h"
#import "ACRMediaTarget.h"
#import "ACROverflowTarget.h"
#import "ACRParseWarning.h"
#import "ACRRegistration.h"
#import "ACRRenderResult.h"
#import "ACRRenderer.h"
#import "ACRRichTextBlockRenderer.h"
#import "ACRTableCellRenderer.h"
#import "ACRTableRenderer.h"
#import "ACRTableRow.h"
#import "ACRTableView.h"
#import "ACRTapGestureRecognizerEventHandler.h"
#import "ACRTapGestureRecognizerFactory.h"
#import "ACRTextBlockRenderer.h"
#import "ACRTextInputHandler.h"
#import "ACRTextView.h"
#import "ACRToggleInputView.h"
#import "ACRView.h"
#import "ACRStringBasedKeyValueObservation.h"
#import "TSExpressionObjCBridge.h"
#import "ACOAuthCardButton.h"
#import "ACOAuthentication.h"
#import "ACOFillerSpaceManager.h"
#import "ACOParseContext.h"
#import "ACORefresh.h"
#import "ACOTokenExchangeResource.h"
#import "ACOTypeaheadDebouncer.h"
#import "ACOTypeaheadDynamicChoicesService.h"
#import "ACOTypeaheadSearchHandler.h"
#import "ACOVisibilityManager.h"
#import "ACOWarning.h"
#import "ACRAVPlayerViewHoldingUIView.h"
#import "ACRActionExecuteRenderer.h"
#import "ACRActionOverflowRenderer.h"
#import "ACRActionToggleVisibilityRenderer.h"
#import "ACRBadgeRenderer.h"
#import "ACRBadgeView.h"
#import "ACRCarouselPageContainerView.h"
#import "ACRCarouselPageView.h"
#import "ACRCarouselView.h"
#import "ACRCarouselViewRenderer.h"
#import "ACRChoiceSetFilteredStyleView.h"
#import "ACRChoiceSetViewDataSource.h"
#import "ACRColumnSetView.h"
#import "ACRColumnView.h"
#import "ACRContentHoldingUIScrollView.h"
#import "ACRContentStackView.h"
#import "ACRCustomActionRenderer.h"
#import "ACRCustomRenderers.h"
#import "ACRDateTextField.h"
#import "ACRDirectionalPanGestureRecognizer.h"
#import "ACREnums.h"
#import "ACRFlowLayout.h"
#import "ACRIContentHoldingView.h"
#import "ACRIFeatureFlagResolver.h"
#import "ACRImageSetUICollectionView.h"
#import "ACRInputTableView.h"
#import "ACRLayoutHelper.h"
#import "ACRNumericTextField.h"
#import "ACRPageControl.h"
#import "ACRQuickReplyMultilineView.h"
#import "ACRQuickReplyView.h"
#import "ACRRatingInputDataSource.h"
#import "ACRRatingView.h"
#import "ACRSeparator.h"
#import "ACRShowCardTarget.h"
#import "ACRTableCellView.h"
#import "ACRTargetBuilder.h"
#import "ACRTargetBuilderDirector.h"
#import "ACRTextField.h"
#import "ACRToggleInputDataSource.h"
#import "ACRToggleVisibilityTarget.h"
#import "ACRTypeaheadSearchParameters.h"
#import "ACRUIImageView.h"
#import "ACRUILabel.h"
#import "ACRViewController.h"
#import "ARCGridViewLayout.h"
#import "AdaptiveCards.h"
#import "UtiliOS.h"
#else
/// Cocoapods Imports
#import <AdaptiveCards/ACOActionOverflow.h>
#import <AdaptiveCards/ACOAdaptiveCard.h>
#import <AdaptiveCards/ACOAdaptiveCardParseResult.h>
#import <AdaptiveCards/ACOBaseCardElement.h>
#import <AdaptiveCards/ACOEnums.h>
#import <AdaptiveCards/ACOHostConfig.h>
#import <AdaptiveCards/ACOHostConfigParseResult.h>
#import <AdaptiveCards/ACOIResourceResolver.h>
#import <AdaptiveCards/ACOInputResults.h>
#import <AdaptiveCards/ACOMediaEvent.h>
#import <AdaptiveCards/ACORemoteResourceInformation.h>
#import <AdaptiveCards/ACORenderContext.h>
#import <AdaptiveCards/ACOResourceResolvers.h>
#import <AdaptiveCards/ACRActionDelegate.h>
#import <AdaptiveCards/ACRActionOpenURLRenderer.h>
#import <AdaptiveCards/ACRActionSetRenderer.h>
#import <AdaptiveCards/ACRActionShowCardRenderer.h>
#import <AdaptiveCards/ACRActionSubmitRenderer.h>
#import <AdaptiveCards/ACRAggregateTarget.h>
#import <AdaptiveCards/ACRBaseActionElementRenderer.h>
#import <AdaptiveCards/ACRBaseCardElementRenderer.h>
#import <AdaptiveCards/ACRBaseTarget.h>
#import <AdaptiveCards/ACRButton.h>
#import <AdaptiveCards/ACRChoiceSetCompactStyleView.h>
#import <AdaptiveCards/ACRColumnRenderer.h>
#import <AdaptiveCards/ACRColumnSetRenderer.h>
#import <AdaptiveCards/ACRContainerRenderer.h>
#import <AdaptiveCards/ACRContentHoldingUIView.h>
#import <AdaptiveCards/ACRErrors.h>
#import <AdaptiveCards/ACRFactSetRenderer.h>
#import <AdaptiveCards/ACRIBaseActionElementRenderer.h>
#import <AdaptiveCards/ACRIBaseCardElementRenderer.h>
#import <AdaptiveCards/ACRIBaseInputHandler.h>
#import <AdaptiveCards/ACRIMedia.h>
#import <AdaptiveCards/ACRImageProperties.h>
#import <AdaptiveCards/ACRImageRenderer.h>
#import <AdaptiveCards/ACRImageSetRenderer.h>
#import <AdaptiveCards/ACRInputChoiceSetRenderer.h>
#import <AdaptiveCards/ACRInputDateRenderer.h>
#import <AdaptiveCards/ACRInputLabelView.h>
#import <AdaptiveCards/ACRInputNumberRenderer.h>
#import <AdaptiveCards/ACRInputRenderer.h>
#import <AdaptiveCards/ACRInputTimeRenderer.h>
#import <AdaptiveCards/ACRInputToggleRenderer.h>
#import <AdaptiveCards/ACRMediaRenderer.h>
#import <AdaptiveCards/ACRMediaTarget.h>
#import <AdaptiveCards/ACROverflowTarget.h>
#import <AdaptiveCards/ACRParseWarning.h>
#import <AdaptiveCards/ACRRegistration.h>
#import <AdaptiveCards/ACRRenderResult.h>
#import <AdaptiveCards/ACRRenderer.h>
#import <AdaptiveCards/ACRRichTextBlockRenderer.h>
#import <AdaptiveCards/ACRTableCellRenderer.h>
#import <AdaptiveCards/ACRTableRenderer.h>
#import <AdaptiveCards/ACRTableRow.h>
#import <AdaptiveCards/ACRTableView.h>
#import <AdaptiveCards/ACRTapGestureRecognizerEventHandler.h>
#import <AdaptiveCards/ACRTapGestureRecognizerFactory.h>
#import <AdaptiveCards/ACRTextBlockRenderer.h>
#import <AdaptiveCards/ACRTextInputHandler.h>
#import <AdaptiveCards/ACRTextView.h>
#import <AdaptiveCards/ACRToggleInputView.h>
#import <AdaptiveCards/ACRView.h>
#import <AdaptiveCards/ACRStringBasedKeyValueObservation.h>
#import <AdaptiveCards/TSExpressionObjCBridge.h>
#import <AdaptiveCards/ACOAuthCardButton.h>
#import <AdaptiveCards/ACOAuthentication.h>
#import <AdaptiveCards/ACOBaseActionElement.h>
#import <AdaptiveCards/ACOFillerSpaceManager.h>
#import <AdaptiveCards/ACOParseContext.h>
#import <AdaptiveCards/ACORefresh.h>
#import <AdaptiveCards/ACOTokenExchangeResource.h>
#import <AdaptiveCards/ACOTypeaheadDebouncer.h>
#import <AdaptiveCards/ACOTypeaheadDynamicChoicesService.h>
#import <AdaptiveCards/ACOTypeaheadSearchHandler.h>
#import <AdaptiveCards/ACOVisibilityManager.h>
#import <AdaptiveCards/ACOWarning.h>
#import <AdaptiveCards/ACRAVPlayerViewHoldingUIView.h>
#import <AdaptiveCards/ACRActionExecuteRenderer.h>
#import <AdaptiveCards/ACRActionOverflowRenderer.h>
#import <AdaptiveCards/ACRActionToggleVisibilityRenderer.h>
#import <AdaptiveCards/ACRBadgeRenderer.h>
#import <AdaptiveCards/ACRBadgeView.h>
#import <AdaptiveCards/ACRCarouselPageContainerView.h>
#import <AdaptiveCards/ACRCarouselPageView.h>
#import <AdaptiveCards/ACRCarouselView.h>
#import <AdaptiveCards/ACRCarouselViewRenderer.h>
#import <AdaptiveCards/ACRChoiceSetFilteredStyleView.h>
#import <AdaptiveCards/ACRChoiceSetViewDataSource.h>
#import <AdaptiveCards/ACRColumnSetView.h>
#import <AdaptiveCards/ACRColumnView.h>
#import <AdaptiveCards/ACRContentHoldingUIScrollView.h>
#import <AdaptiveCards/ACRContentStackView.h>
#import <AdaptiveCards/ACRCustomActionRenderer.h>
#import <AdaptiveCards/ACRCustomRenderers.h>
#import <AdaptiveCards/ACRDateTextField.h>
#import <AdaptiveCards/ACRDirectionalPanGestureRecognizer.h>
#import <AdaptiveCards/ACREnums.h>
#import <AdaptiveCards/ACRFlowLayout.h>
#import <AdaptiveCards/ACRIContentHoldingView.h>
#import <AdaptiveCards/ACRIFeatureFlagResolver.h>
#import <AdaptiveCards/ACRImageSetUICollectionView.h>
#import <AdaptiveCards/ACRInputTableView.h>
#import <AdaptiveCards/ACRLayoutHelper.h>
#import <AdaptiveCards/ACRNumericTextField.h>
#import <AdaptiveCards/ACRPageControl.h>
#import <AdaptiveCards/ACRQuickReplyMultilineView.h>
#import <AdaptiveCards/ACRQuickReplyView.h>
#import <AdaptiveCards/ACRRatingInputDataSource.h>
#import <AdaptiveCards/ACRRatingView.h>
#import <AdaptiveCards/ACRSeparator.h>
#import <AdaptiveCards/ACRShowCardTarget.h>
#import <AdaptiveCards/ACRTableCellView.h>
#import <AdaptiveCards/ACRTargetBuilder.h>
#import <AdaptiveCards/ACRTargetBuilderDirector.h>
#import <AdaptiveCards/ACRTextField.h>
#import <AdaptiveCards/ACRToggleInputDataSource.h>
#import <AdaptiveCards/ACRToggleVisibilityTarget.h>
#import <AdaptiveCards/ACRTypeaheadSearchParameters.h>
#import <AdaptiveCards/ACRUIImageView.h>
#import <AdaptiveCards/ACRUILabel.h>
#import <AdaptiveCards/ACRViewController.h>
#import <AdaptiveCards/ARCGridViewLayout.h>
#import <AdaptiveCards/AdaptiveCards.h>
#import <AdaptiveCards/UtiliOS.h>

#endif
