/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public enum ActionRole {
  Button(0),
  Link,
  Tab,
  Menu,
  MenuItem;

  public final int swigValue() {
    return swigValue;
  }

  public static ActionRole swigToEnum(int swigValue) {
    ActionRole[] swigValues = ActionRole.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ActionRole swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ActionRole.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ActionRole() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ActionRole(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ActionRole(ActionRole swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

