/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class AdaptiveCardObjectModel implements AdaptiveCardObjectModelConstants {
  public static String getC_sharedModelVersion() {
    return AdaptiveCardObjectModelJNI.c_sharedModelVersion_get();
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__AdaptiveCardSchemaKey_t getAdaptiveCardSchemaKeyEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__AdaptiveCardSchemaKey_t(AdaptiveCardObjectModelJNI.getAdaptiveCardSchemaKeyEnum(), false);
  }

  public static String AdaptiveCardSchemaKeyToString(AdaptiveCardSchemaKey t) {
    return AdaptiveCardObjectModelJNI.AdaptiveCardSchemaKeyToString(t.swigValue());
  }

  public static AdaptiveCardSchemaKey AdaptiveCardSchemaKeyFromString(String t) {
    return AdaptiveCardSchemaKey.swigToEnum(AdaptiveCardObjectModelJNI.AdaptiveCardSchemaKeyFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__CardElementType_t getCardElementTypeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__CardElementType_t(AdaptiveCardObjectModelJNI.getCardElementTypeEnum(), false);
  }

  public static String CardElementTypeToString(CardElementType t) {
    return AdaptiveCardObjectModelJNI.CardElementTypeToString(t.swigValue());
  }

  public static CardElementType CardElementTypeFromString(String t) {
    return CardElementType.swigToEnum(AdaptiveCardObjectModelJNI.CardElementTypeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__InlineElementType_t getInlineElementTypeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__InlineElementType_t(AdaptiveCardObjectModelJNI.getInlineElementTypeEnum(), false);
  }

  public static String InlineElementTypeToString(InlineElementType t) {
    return AdaptiveCardObjectModelJNI.InlineElementTypeToString(t.swigValue());
  }

  public static InlineElementType InlineElementTypeFromString(String t) {
    return InlineElementType.swigToEnum(AdaptiveCardObjectModelJNI.InlineElementTypeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__TextStyle_t getTextStyleEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__TextStyle_t(AdaptiveCardObjectModelJNI.getTextStyleEnum(), false);
  }

  public static String TextStyleToString(TextStyle t) {
    return AdaptiveCardObjectModelJNI.TextStyleToString(t.swigValue());
  }

  public static TextStyle TextStyleFromString(String t) {
    return TextStyle.swigToEnum(AdaptiveCardObjectModelJNI.TextStyleFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__TextSize_t getTextSizeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__TextSize_t(AdaptiveCardObjectModelJNI.getTextSizeEnum(), false);
  }

  public static String TextSizeToString(TextSize t) {
    return AdaptiveCardObjectModelJNI.TextSizeToString(t.swigValue());
  }

  public static TextSize TextSizeFromString(String t) {
    return TextSize.swigToEnum(AdaptiveCardObjectModelJNI.TextSizeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__TextWeight_t getTextWeightEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__TextWeight_t(AdaptiveCardObjectModelJNI.getTextWeightEnum(), false);
  }

  public static String TextWeightToString(TextWeight t) {
    return AdaptiveCardObjectModelJNI.TextWeightToString(t.swigValue());
  }

  public static TextWeight TextWeightFromString(String t) {
    return TextWeight.swigToEnum(AdaptiveCardObjectModelJNI.TextWeightFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__FontType_t getFontTypeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__FontType_t(AdaptiveCardObjectModelJNI.getFontTypeEnum(), false);
  }

  public static String FontTypeToString(FontType t) {
    return AdaptiveCardObjectModelJNI.FontTypeToString(t.swigValue());
  }

  public static FontType FontTypeFromString(String t) {
    return FontType.swigToEnum(AdaptiveCardObjectModelJNI.FontTypeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ForegroundColor_t getForegroundColorEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ForegroundColor_t(AdaptiveCardObjectModelJNI.getForegroundColorEnum(), false);
  }

  public static String ForegroundColorToString(ForegroundColor t) {
    return AdaptiveCardObjectModelJNI.ForegroundColorToString(t.swigValue());
  }

  public static ForegroundColor ForegroundColorFromString(String t) {
    return ForegroundColor.swigToEnum(AdaptiveCardObjectModelJNI.ForegroundColorFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__HorizontalAlignment_t getHorizontalAlignmentEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__HorizontalAlignment_t(AdaptiveCardObjectModelJNI.getHorizontalAlignmentEnum(), false);
  }

  public static String HorizontalAlignmentToString(HorizontalAlignment t) {
    return AdaptiveCardObjectModelJNI.HorizontalAlignmentToString(t.swigValue());
  }

  public static HorizontalAlignment HorizontalAlignmentFromString(String t) {
    return HorizontalAlignment.swigToEnum(AdaptiveCardObjectModelJNI.HorizontalAlignmentFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__HorizontalContentAlignment_t getHorizontalContentAlignmentEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__HorizontalContentAlignment_t(AdaptiveCardObjectModelJNI.getHorizontalContentAlignmentEnum(), false);
  }

  public static String HorizontalContentAlignmentToString(HorizontalContentAlignment t) {
    return AdaptiveCardObjectModelJNI.HorizontalContentAlignmentToString(t.swigValue());
  }

  public static HorizontalContentAlignment HorizontalContentAlignmentFromString(String t) {
    return HorizontalContentAlignment.swigToEnum(AdaptiveCardObjectModelJNI.HorizontalContentAlignmentFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__VerticalAlignment_t getVerticalAlignmentEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__VerticalAlignment_t(AdaptiveCardObjectModelJNI.getVerticalAlignmentEnum(), false);
  }

  public static String VerticalAlignmentToString(VerticalAlignment t) {
    return AdaptiveCardObjectModelJNI.VerticalAlignmentToString(t.swigValue());
  }

  public static VerticalAlignment VerticalAlignmentFromString(String t) {
    return VerticalAlignment.swigToEnum(AdaptiveCardObjectModelJNI.VerticalAlignmentFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__VerticalContentAlignment_t getVerticalContentAlignmentEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__VerticalContentAlignment_t(AdaptiveCardObjectModelJNI.getVerticalContentAlignmentEnum(), false);
  }

  public static String VerticalContentAlignmentToString(VerticalContentAlignment t) {
    return AdaptiveCardObjectModelJNI.VerticalContentAlignmentToString(t.swigValue());
  }

  public static VerticalContentAlignment VerticalContentAlignmentFromString(String t) {
    return VerticalContentAlignment.swigToEnum(AdaptiveCardObjectModelJNI.VerticalContentAlignmentFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__IconSize_t getIconSizeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__IconSize_t(AdaptiveCardObjectModelJNI.getIconSizeEnum(), false);
  }

  public static String IconSizeToString(IconSize t) {
    return AdaptiveCardObjectModelJNI.IconSizeToString(t.swigValue());
  }

  public static IconSize IconSizeFromString(String t) {
    return IconSize.swigToEnum(AdaptiveCardObjectModelJNI.IconSizeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__IconStyle_t getIconStyleEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__IconStyle_t(AdaptiveCardObjectModelJNI.getIconStyleEnum(), false);
  }

  public static String IconStyleToString(IconStyle t) {
    return AdaptiveCardObjectModelJNI.IconStyleToString(t.swigValue());
  }

  public static IconStyle IconStyleFromString(String t) {
    return IconStyle.swigToEnum(AdaptiveCardObjectModelJNI.IconStyleFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ImageFillMode_t getImageFillModeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ImageFillMode_t(AdaptiveCardObjectModelJNI.getImageFillModeEnum(), false);
  }

  public static String ImageFillModeToString(ImageFillMode t) {
    return AdaptiveCardObjectModelJNI.ImageFillModeToString(t.swigValue());
  }

  public static ImageFillMode ImageFillModeFromString(String t) {
    return ImageFillMode.swigToEnum(AdaptiveCardObjectModelJNI.ImageFillModeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ItemFit_t getItemFitEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ItemFit_t(AdaptiveCardObjectModelJNI.getItemFitEnum(), false);
  }

  public static String ItemFitToString(ItemFit t) {
    return AdaptiveCardObjectModelJNI.ItemFitToString(t.swigValue());
  }

  public static ItemFit ItemFitFromString(String t) {
    return ItemFit.swigToEnum(AdaptiveCardObjectModelJNI.ItemFitFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__LayoutContainerType_t getLayoutContainerTypeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__LayoutContainerType_t(AdaptiveCardObjectModelJNI.getLayoutContainerTypeEnum(), false);
  }

  public static String LayoutContainerTypeToString(LayoutContainerType t) {
    return AdaptiveCardObjectModelJNI.LayoutContainerTypeToString(t.swigValue());
  }

  public static LayoutContainerType LayoutContainerTypeFromString(String t) {
    return LayoutContainerType.swigToEnum(AdaptiveCardObjectModelJNI.LayoutContainerTypeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ImageStyle_t getImageStyleEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ImageStyle_t(AdaptiveCardObjectModelJNI.getImageStyleEnum(), false);
  }

  public static String ImageStyleToString(ImageStyle t) {
    return AdaptiveCardObjectModelJNI.ImageStyleToString(t.swigValue());
  }

  public static ImageStyle ImageStyleFromString(String t) {
    return ImageStyle.swigToEnum(AdaptiveCardObjectModelJNI.ImageStyleFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ImageSize_t getImageSizeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ImageSize_t(AdaptiveCardObjectModelJNI.getImageSizeEnum(), false);
  }

  public static String ImageSizeToString(ImageSize t) {
    return AdaptiveCardObjectModelJNI.ImageSizeToString(t.swigValue());
  }

  public static ImageSize ImageSizeFromString(String t) {
    return ImageSize.swigToEnum(AdaptiveCardObjectModelJNI.ImageSizeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ImageFitMode_t getImageFitModeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ImageFitMode_t(AdaptiveCardObjectModelJNI.getImageFitModeEnum(), false);
  }

  public static String ImageFitModeToString(ImageFitMode t) {
    return AdaptiveCardObjectModelJNI.ImageFitModeToString(t.swigValue());
  }

  public static ImageFitMode ImageFitModeFromString(String t) {
    return ImageFitMode.swigToEnum(AdaptiveCardObjectModelJNI.ImageFitModeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__TextInputStyle_t getTextInputStyleEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__TextInputStyle_t(AdaptiveCardObjectModelJNI.getTextInputStyleEnum(), false);
  }

  public static String TextInputStyleToString(TextInputStyle t) {
    return AdaptiveCardObjectModelJNI.TextInputStyleToString(t.swigValue());
  }

  public static TextInputStyle TextInputStyleFromString(String t) {
    return TextInputStyle.swigToEnum(AdaptiveCardObjectModelJNI.TextInputStyleFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ActionType_t getActionTypeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ActionType_t(AdaptiveCardObjectModelJNI.getActionTypeEnum(), false);
  }

  public static String ActionTypeToString(ActionType t) {
    return AdaptiveCardObjectModelJNI.ActionTypeToString(t.swigValue());
  }

  public static ActionType ActionTypeFromString(String t) {
    return ActionType.swigToEnum(AdaptiveCardObjectModelJNI.ActionTypeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ActionAlignment_t getActionAlignmentEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ActionAlignment_t(AdaptiveCardObjectModelJNI.getActionAlignmentEnum(), false);
  }

  public static String ActionAlignmentToString(ActionAlignment t) {
    return AdaptiveCardObjectModelJNI.ActionAlignmentToString(t.swigValue());
  }

  public static ActionAlignment ActionAlignmentFromString(String t) {
    return ActionAlignment.swigToEnum(AdaptiveCardObjectModelJNI.ActionAlignmentFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__AssociatedInputs_t getAssociatedInputsEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__AssociatedInputs_t(AdaptiveCardObjectModelJNI.getAssociatedInputsEnum(), false);
  }

  public static String AssociatedInputsToString(AssociatedInputs t) {
    return AdaptiveCardObjectModelJNI.AssociatedInputsToString(t.swigValue());
  }

  public static AssociatedInputs AssociatedInputsFromString(String t) {
    return AssociatedInputs.swigToEnum(AdaptiveCardObjectModelJNI.AssociatedInputsFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ChoiceSetStyle_t getChoiceSetStyleEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ChoiceSetStyle_t(AdaptiveCardObjectModelJNI.getChoiceSetStyleEnum(), false);
  }

  public static String ChoiceSetStyleToString(ChoiceSetStyle t) {
    return AdaptiveCardObjectModelJNI.ChoiceSetStyleToString(t.swigValue());
  }

  public static ChoiceSetStyle ChoiceSetStyleFromString(String t) {
    return ChoiceSetStyle.swigToEnum(AdaptiveCardObjectModelJNI.ChoiceSetStyleFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__SeparatorThickness_t getSeparatorThicknessEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__SeparatorThickness_t(AdaptiveCardObjectModelJNI.getSeparatorThicknessEnum(), false);
  }

  public static String SeparatorThicknessToString(SeparatorThickness t) {
    return AdaptiveCardObjectModelJNI.SeparatorThicknessToString(t.swigValue());
  }

  public static SeparatorThickness SeparatorThicknessFromString(String t) {
    return SeparatorThickness.swigToEnum(AdaptiveCardObjectModelJNI.SeparatorThicknessFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__Spacing_t getSpacingEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__Spacing_t(AdaptiveCardObjectModelJNI.getSpacingEnum(), false);
  }

  public static String SpacingToString(Spacing t) {
    return AdaptiveCardObjectModelJNI.SpacingToString(t.swigValue());
  }

  public static Spacing SpacingFromString(String t) {
    return Spacing.swigToEnum(AdaptiveCardObjectModelJNI.SpacingFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ActionsOrientation_t getActionsOrientationEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ActionsOrientation_t(AdaptiveCardObjectModelJNI.getActionsOrientationEnum(), false);
  }

  public static String ActionsOrientationToString(ActionsOrientation t) {
    return AdaptiveCardObjectModelJNI.ActionsOrientationToString(t.swigValue());
  }

  public static ActionsOrientation ActionsOrientationFromString(String t) {
    return ActionsOrientation.swigToEnum(AdaptiveCardObjectModelJNI.ActionsOrientationFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ActionMode_t getActionModeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ActionMode_t(AdaptiveCardObjectModelJNI.getActionModeEnum(), false);
  }

  public static String ActionModeToString(ActionMode t) {
    return AdaptiveCardObjectModelJNI.ActionModeToString(t.swigValue());
  }

  public static ActionMode ActionModeFromString(String t) {
    return ActionMode.swigToEnum(AdaptiveCardObjectModelJNI.ActionModeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ActionRole_t getActionRoleEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ActionRole_t(AdaptiveCardObjectModelJNI.getActionRoleEnum(), false);
  }

  public static String ActionRoleToString(ActionRole t) {
    return AdaptiveCardObjectModelJNI.ActionRoleToString(t.swigValue());
  }

  public static ActionRole ActionRoleFromString(String t) {
    return ActionRole.swigToEnum(AdaptiveCardObjectModelJNI.ActionRoleFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ContainerStyle_t getContainerStyleEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ContainerStyle_t(AdaptiveCardObjectModelJNI.getContainerStyleEnum(), false);
  }

  public static String ContainerStyleToString(ContainerStyle t) {
    return AdaptiveCardObjectModelJNI.ContainerStyleToString(t.swigValue());
  }

  public static ContainerStyle ContainerStyleFromString(String t) {
    return ContainerStyle.swigToEnum(AdaptiveCardObjectModelJNI.ContainerStyleFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__Mode_t getModeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__Mode_t(AdaptiveCardObjectModelJNI.getModeEnum(), false);
  }

  public static String ModeToString(Mode t) {
    return AdaptiveCardObjectModelJNI.ModeToString(t.swigValue());
  }

  public static Mode ModeFromString(String t) {
    return Mode.swigToEnum(AdaptiveCardObjectModelJNI.ModeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ACTheme_t getACThemeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ACTheme_t(AdaptiveCardObjectModelJNI.getACThemeEnum(), false);
  }

  public static String ACThemeToString(ACTheme t) {
    return AdaptiveCardObjectModelJNI.ACThemeToString(t.swigValue());
  }

  public static ACTheme ACThemeFromString(String t) {
    return ACTheme.swigToEnum(AdaptiveCardObjectModelJNI.ACThemeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ErrorStatusCode_t getErrorStatusCodeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ErrorStatusCode_t(AdaptiveCardObjectModelJNI.getErrorStatusCodeEnum(), false);
  }

  public static String ErrorStatusCodeToString(ErrorStatusCode t) {
    return AdaptiveCardObjectModelJNI.ErrorStatusCodeToString(t.swigValue());
  }

  public static ErrorStatusCode ErrorStatusCodeFromString(String t) {
    return ErrorStatusCode.swigToEnum(AdaptiveCardObjectModelJNI.ErrorStatusCodeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__IconPlacement_t getIconPlacementEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__IconPlacement_t(AdaptiveCardObjectModelJNI.getIconPlacementEnum(), false);
  }

  public static String IconPlacementToString(IconPlacement t) {
    return AdaptiveCardObjectModelJNI.IconPlacementToString(t.swigValue());
  }

  public static IconPlacement IconPlacementFromString(String t) {
    return IconPlacement.swigToEnum(AdaptiveCardObjectModelJNI.IconPlacementFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__PageAnimation_t getPageAnimationEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__PageAnimation_t(AdaptiveCardObjectModelJNI.getPageAnimationEnum(), false);
  }

  public static String PageAnimationToString(PageAnimation t) {
    return AdaptiveCardObjectModelJNI.PageAnimationToString(t.swigValue());
  }

  public static PageAnimation PageAnimationFromString(String t) {
    return PageAnimation.swigToEnum(AdaptiveCardObjectModelJNI.PageAnimationFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__HeightType_t getHeightTypeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__HeightType_t(AdaptiveCardObjectModelJNI.getHeightTypeEnum(), false);
  }

  public static String HeightTypeToString(HeightType t) {
    return AdaptiveCardObjectModelJNI.HeightTypeToString(t.swigValue());
  }

  public static HeightType HeightTypeFromString(String t) {
    return HeightType.swigToEnum(AdaptiveCardObjectModelJNI.HeightTypeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__RatingSize_t getRatingSizeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__RatingSize_t(AdaptiveCardObjectModelJNI.getRatingSizeEnum(), false);
  }

  public static String RatingSizeToString(RatingSize t) {
    return AdaptiveCardObjectModelJNI.RatingSizeToString(t.swigValue());
  }

  public static RatingSize RatingSizeFromString(String t) {
    return RatingSize.swigToEnum(AdaptiveCardObjectModelJNI.RatingSizeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__RatingColor_t getRatingColorEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__RatingColor_t(AdaptiveCardObjectModelJNI.getRatingColorEnum(), false);
  }

  public static String RatingColorToString(RatingColor t) {
    return AdaptiveCardObjectModelJNI.RatingColorToString(t.swigValue());
  }

  public static RatingColor RatingColorFromString(String t) {
    return RatingColor.swigToEnum(AdaptiveCardObjectModelJNI.RatingColorFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__RatingStyle_t getRatingStyleEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__RatingStyle_t(AdaptiveCardObjectModelJNI.getRatingStyleEnum(), false);
  }

  public static String RatingStyleToString(RatingStyle t) {
    return AdaptiveCardObjectModelJNI.RatingStyleToString(t.swigValue());
  }

  public static RatingStyle RatingStyleFromString(String t) {
    return RatingStyle.swigToEnum(AdaptiveCardObjectModelJNI.RatingStyleFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__TargetWidthType_t getTargetWidthTypeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__TargetWidthType_t(AdaptiveCardObjectModelJNI.getTargetWidthTypeEnum(), false);
  }

  public static String TargetWidthTypeToString(TargetWidthType t) {
    return AdaptiveCardObjectModelJNI.TargetWidthTypeToString(t.swigValue());
  }

  public static TargetWidthType TargetWidthTypeFromString(String t) {
    return TargetWidthType.swigToEnum(AdaptiveCardObjectModelJNI.TargetWidthTypeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ValueChangedActionType_t getValueChangedActionTypeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ValueChangedActionType_t(AdaptiveCardObjectModelJNI.getValueChangedActionTypeEnum(), false);
  }

  public static String ValueChangedActionTypeToString(ValueChangedActionType t) {
    return AdaptiveCardObjectModelJNI.ValueChangedActionTypeToString(t.swigValue());
  }

  public static ValueChangedActionType ValueChangedActionTypeFromString(String t) {
    return ValueChangedActionType.swigToEnum(AdaptiveCardObjectModelJNI.ValueChangedActionTypeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__IconPosition_t getIconPositionEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__IconPosition_t(AdaptiveCardObjectModelJNI.getIconPositionEnum(), false);
  }

  public static String IconPositionToString(IconPosition t) {
    return AdaptiveCardObjectModelJNI.IconPositionToString(t.swigValue());
  }

  public static IconPosition IconPositionFromString(String t) {
    return IconPosition.swigToEnum(AdaptiveCardObjectModelJNI.IconPositionFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__Shape_t getShapeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__Shape_t(AdaptiveCardObjectModelJNI.getShapeEnum(), false);
  }

  public static String ShapeToString(Shape t) {
    return AdaptiveCardObjectModelJNI.ShapeToString(t.swigValue());
  }

  public static Shape ShapeFromString(String t) {
    return Shape.swigToEnum(AdaptiveCardObjectModelJNI.ShapeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__LabelPosition_t getLabelPositionEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__LabelPosition_t(AdaptiveCardObjectModelJNI.getLabelPositionEnum(), false);
  }

  public static String LabelPositionToString(LabelPosition t) {
    return AdaptiveCardObjectModelJNI.LabelPositionToString(t.swigValue());
  }

  public static LabelPosition LabelPositionFromString(String t) {
    return LabelPosition.swigToEnum(AdaptiveCardObjectModelJNI.LabelPositionFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ProgressSize_t getProgressSizeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ProgressSize_t(AdaptiveCardObjectModelJNI.getProgressSizeEnum(), false);
  }

  public static String ProgressSizeToString(ProgressSize t) {
    return AdaptiveCardObjectModelJNI.ProgressSizeToString(t.swigValue());
  }

  public static ProgressSize ProgressSizeFromString(String t) {
    return ProgressSize.swigToEnum(AdaptiveCardObjectModelJNI.ProgressSizeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__BadgeStyle_t getBadgeStyleEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__BadgeStyle_t(AdaptiveCardObjectModelJNI.getBadgeStyleEnum(), false);
  }

  public static String BadgeStyleToString(BadgeStyle t) {
    return AdaptiveCardObjectModelJNI.BadgeStyleToString(t.swigValue());
  }

  public static BadgeStyle BadgeStyleFromString(String t) {
    return BadgeStyle.swigToEnum(AdaptiveCardObjectModelJNI.BadgeStyleFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__BadgeSize_t getBadgeSizeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__BadgeSize_t(AdaptiveCardObjectModelJNI.getBadgeSizeEnum(), false);
  }

  public static String BadgeSizeToString(BadgeSize t) {
    return AdaptiveCardObjectModelJNI.BadgeSizeToString(t.swigValue());
  }

  public static BadgeSize BadgeSizeFromString(String t) {
    return BadgeSize.swigToEnum(AdaptiveCardObjectModelJNI.BadgeSizeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__BadgeAppearance_t getBadgeAppearanceEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__BadgeAppearance_t(AdaptiveCardObjectModelJNI.getBadgeAppearanceEnum(), false);
  }

  public static String BadgeAppearanceToString(BadgeAppearance t) {
    return AdaptiveCardObjectModelJNI.BadgeAppearanceToString(t.swigValue());
  }

  public static BadgeAppearance BadgeAppearanceFromString(String t) {
    return BadgeAppearance.swigToEnum(AdaptiveCardObjectModelJNI.BadgeAppearanceFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ProgressBarColor_t getProgressBarColorEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ProgressBarColor_t(AdaptiveCardObjectModelJNI.getProgressBarColorEnum(), false);
  }

  public static String ProgressBarColorToString(ProgressBarColor t) {
    return AdaptiveCardObjectModelJNI.ProgressBarColorToString(t.swigValue());
  }

  public static ProgressBarColor ProgressBarColorFromString(String t) {
    return ProgressBarColor.swigToEnum(AdaptiveCardObjectModelJNI.ProgressBarColorFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ReferenceType_t getReferenceTypeEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ReferenceType_t(AdaptiveCardObjectModelJNI.getReferenceTypeEnum(), false);
  }

  public static String ReferenceTypeToString(ReferenceType t) {
    return AdaptiveCardObjectModelJNI.ReferenceTypeToString(t.swigValue());
  }

  public static ReferenceType ReferenceTypeFromString(String t) {
    return ReferenceType.swigToEnum(AdaptiveCardObjectModelJNI.ReferenceTypeFromString(t));
  }

  public static SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ReferenceIcon_t getReferenceIconEnum() {
    return new SWIGTYPE_p_AdaptiveCards__EnumHelpers__EnumMappingT_AdaptiveCards__ReferenceIcon_t(AdaptiveCardObjectModelJNI.getReferenceIconEnum(), false);
  }

  public static String ReferenceIconToString(ReferenceIcon t) {
    return AdaptiveCardObjectModelJNI.ReferenceIconToString(t.swigValue());
  }

  public static ReferenceIcon ReferenceIconFromString(String t) {
    return ReferenceIcon.swigToEnum(AdaptiveCardObjectModelJNI.ReferenceIconFromString(t));
  }

  public static void HandleUnknownProperties(JsonValue json, SWIGTYPE_p_std__unordered_setT_std__string_t knownProperties, JsonValue unknownProperties) {
    AdaptiveCardObjectModelJNI.HandleUnknownProperties(JsonValue.getCPtr(json), json, SWIGTYPE_p_std__unordered_setT_std__string_t.getCPtr(knownProperties), JsonValue.getCPtr(unknownProperties), unknownProperties);
  }

  public static String getC_adaptiveCardsFeature() {
    return AdaptiveCardObjectModelJNI.c_adaptiveCardsFeature_get();
  }

  public static String ToLowercase(String value) {
    return AdaptiveCardObjectModelJNI.ToLowercase(value);
  }

  public static void setDEFAULT_IMAGE_FIT_MODE(ImageFitMode value) {
    AdaptiveCardObjectModelJNI.DEFAULT_IMAGE_FIT_MODE_set(value.swigValue());
  }

  public static ImageFitMode getDEFAULT_IMAGE_FIT_MODE() {
    return ImageFitMode.swigToEnum(AdaptiveCardObjectModelJNI.DEFAULT_IMAGE_FIT_MODE_get());
  }

  public static void setDEFAULT_HORIZONTAL_CONTENT_ALIGNMENT(HorizontalContentAlignment value) {
    AdaptiveCardObjectModelJNI.DEFAULT_HORIZONTAL_CONTENT_ALIGNMENT_set(value.swigValue());
  }

  public static HorizontalContentAlignment getDEFAULT_HORIZONTAL_CONTENT_ALIGNMENT() {
    return HorizontalContentAlignment.swigToEnum(AdaptiveCardObjectModelJNI.DEFAULT_HORIZONTAL_CONTENT_ALIGNMENT_get());
  }

  public static void setDEFAULT_VERTICAL_CONTENT_ALIGNMENT(VerticalContentAlignment value) {
    AdaptiveCardObjectModelJNI.DEFAULT_VERTICAL_CONTENT_ALIGNMENT_set(value.swigValue());
  }

  public static VerticalContentAlignment getDEFAULT_VERTICAL_CONTENT_ALIGNMENT() {
    return VerticalContentAlignment.swigToEnum(AdaptiveCardObjectModelJNI.DEFAULT_VERTICAL_CONTENT_ALIGNMENT_get());
  }

}
