/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class AreaGridLayout extends Layout {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected AreaGridLayout(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.AreaGridLayout_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AreaGridLayout obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_AreaGridLayout(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AreaGridLayout() {
    this(AdaptiveCardObjectModelJNI.new_AreaGridLayout__SWIG_0(), true);
  }

  public AreaGridLayout(AreaGridLayout arg0) {
    this(AdaptiveCardObjectModelJNI.new_AreaGridLayout__SWIG_1(AreaGridLayout.getCPtr(arg0), arg0), true);
  }

  public StringVector GetColumns() {
    return new StringVector(AdaptiveCardObjectModelJNI.AreaGridLayout_GetColumns(swigCPtr, this), false);
  }

  public void SetColumns(StringVector arg0) {
    AdaptiveCardObjectModelJNI.AreaGridLayout_SetColumns(swigCPtr, this, StringVector.getCPtr(arg0), arg0);
  }

  public GridAreaVector GetAreas() {
    return new GridAreaVector(AdaptiveCardObjectModelJNI.AreaGridLayout_GetAreas__SWIG_0(swigCPtr, this), false);
  }

  public void SetAreas(GridAreaVector value) {
    AdaptiveCardObjectModelJNI.AreaGridLayout_SetAreas(swigCPtr, this, GridAreaVector.getCPtr(value), value);
  }

  public Spacing GetColumnSpacing() {
    return Spacing.swigToEnum(AdaptiveCardObjectModelJNI.AreaGridLayout_GetColumnSpacing(swigCPtr, this));
  }

  public void SetColumnSpacing(Spacing value) {
    AdaptiveCardObjectModelJNI.AreaGridLayout_SetColumnSpacing(swigCPtr, this, value.swigValue());
  }

  public Spacing GetRowSpacing() {
    return Spacing.swigToEnum(AdaptiveCardObjectModelJNI.AreaGridLayout_GetRowSpacing(swigCPtr, this));
  }

  public void SetRowSpacing(Spacing value) {
    AdaptiveCardObjectModelJNI.AreaGridLayout_SetRowSpacing(swigCPtr, this, value.swigValue());
  }

  public boolean ShouldSerialize() {
    return AdaptiveCardObjectModelJNI.AreaGridLayout_ShouldSerialize(swigCPtr, this);
  }

  public String Serialize() {
    return AdaptiveCardObjectModelJNI.AreaGridLayout_Serialize(swigCPtr, this);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.AreaGridLayout_SerializeToJsonValue(swigCPtr, this), true);
  }

  public static AreaGridLayout Deserialize(JsonValue json) {
    long cPtr = AdaptiveCardObjectModelJNI.AreaGridLayout_Deserialize(JsonValue.getCPtr(json), json);
    return (cPtr == 0) ? null : new AreaGridLayout(cPtr, true);
  }

  public static AreaGridLayout DeserializeFromString(String jsonString) {
    long cPtr = AdaptiveCardObjectModelJNI.AreaGridLayout_DeserializeFromString(jsonString);
    return (cPtr == 0) ? null : new AreaGridLayout(cPtr, true);
  }

}
