/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class AreaGridLayoutVector extends java.util.AbstractList<AreaGridLayout> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AreaGridLayoutVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AreaGridLayoutVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_AreaGridLayoutVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AreaGridLayoutVector(AreaGridLayout[] initialElements) {
    this();
    reserve(initialElements.length);

    for (AreaGridLayout element : initialElements) {
      add(element);
    }
  }

  public AreaGridLayoutVector(Iterable<AreaGridLayout> initialElements) {
    this();
    for (AreaGridLayout element : initialElements) {
      add(element);
    }
  }

  public AreaGridLayout get(int index) {
    return doGet(index);
  }

  public AreaGridLayout set(int index, AreaGridLayout e) {
    return doSet(index, e);
  }

  public boolean add(AreaGridLayout e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, AreaGridLayout e) {
    modCount++;
    doAdd(index, e);
  }

  public AreaGridLayout remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public AreaGridLayoutVector() {
    this(AdaptiveCardObjectModelJNI.new_AreaGridLayoutVector__SWIG_0(), true);
  }

  public AreaGridLayoutVector(AreaGridLayoutVector other) {
    this(AdaptiveCardObjectModelJNI.new_AreaGridLayoutVector__SWIG_1(AreaGridLayoutVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return AdaptiveCardObjectModelJNI.AreaGridLayoutVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AdaptiveCardObjectModelJNI.AreaGridLayoutVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AdaptiveCardObjectModelJNI.AreaGridLayoutVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AdaptiveCardObjectModelJNI.AreaGridLayoutVector_clear(swigCPtr, this);
  }

  public AreaGridLayoutVector(int count, AreaGridLayout value) {
    this(AdaptiveCardObjectModelJNI.new_AreaGridLayoutVector__SWIG_2(count, AreaGridLayout.getCPtr(value), value), true);
  }

  private int doSize() {
    return AdaptiveCardObjectModelJNI.AreaGridLayoutVector_doSize(swigCPtr, this);
  }

  private void doAdd(AreaGridLayout x) {
    AdaptiveCardObjectModelJNI.AreaGridLayoutVector_doAdd__SWIG_0(swigCPtr, this, AreaGridLayout.getCPtr(x), x);
  }

  private void doAdd(int index, AreaGridLayout x) {
    AdaptiveCardObjectModelJNI.AreaGridLayoutVector_doAdd__SWIG_1(swigCPtr, this, index, AreaGridLayout.getCPtr(x), x);
  }

  private AreaGridLayout doRemove(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.AreaGridLayoutVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new AreaGridLayout(cPtr, true);
  }

  private AreaGridLayout doGet(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.AreaGridLayoutVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new AreaGridLayout(cPtr, true);
  }

  private AreaGridLayout doSet(int index, AreaGridLayout val) {
    long cPtr = AdaptiveCardObjectModelJNI.AreaGridLayoutVector_doSet(swigCPtr, this, index, AreaGridLayout.getCPtr(val), val);
    return (cPtr == 0) ? null : new AreaGridLayout(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AdaptiveCardObjectModelJNI.AreaGridLayoutVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
