/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class Badge extends BaseCardElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected Badge(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.Badge_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Badge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_Badge(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Badge() {
    this(AdaptiveCardObjectModelJNI.new_Badge__SWIG_0(), true);
  }

  public Badge(Badge arg0) {
    this(AdaptiveCardObjectModelJNI.new_Badge__SWIG_1(Badge.getCPtr(arg0), arg0), true);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.Badge_SerializeToJsonValue(swigCPtr, this), true);
  }

  public @androidx.annotation.Nullable HorizontalAlignment GetHorizontalAlignment() {
    StdOptionalHorizontalAlignment optvalue = new StdOptionalHorizontalAlignment(AdaptiveCardObjectModelJNI.Badge_GetHorizontalAlignment(swigCPtr, this), false);
    return optvalue.has_value() ? optvalue.value() : null;
  }

  public void SetHorizontalAlignment(@androidx.annotation.Nullable HorizontalAlignment value) {
    StdOptionalHorizontalAlignment optvalue = (value == null) ? new StdOptionalHorizontalAlignment() : new StdOptionalHorizontalAlignment(value);
    {
      AdaptiveCardObjectModelJNI.Badge_SetHorizontalAlignment(swigCPtr, this, StdOptionalHorizontalAlignment.getCPtr(optvalue), optvalue);
    }
  }

  public String GetText() {
    return AdaptiveCardObjectModelJNI.Badge_GetText(swigCPtr, this);
  }

  public void SetText(String value) {
    AdaptiveCardObjectModelJNI.Badge_SetText(swigCPtr, this, value);
  }

  public String GetBadgeIcon() {
    return AdaptiveCardObjectModelJNI.Badge_GetBadgeIcon(swigCPtr, this);
  }

  public void SetBadgeIcon(String value) {
    AdaptiveCardObjectModelJNI.Badge_SetBadgeIcon(swigCPtr, this, value);
  }

  public String GetTooltip() {
    return AdaptiveCardObjectModelJNI.Badge_GetTooltip(swigCPtr, this);
  }

  public void SetTooltip(String value) {
    AdaptiveCardObjectModelJNI.Badge_SetTooltip(swigCPtr, this, value);
  }

  public BadgeStyle GetBadgeStyle() {
    return BadgeStyle.swigToEnum(AdaptiveCardObjectModelJNI.Badge_GetBadgeStyle(swigCPtr, this));
  }

  public void SetBadgeStyle(BadgeStyle value) {
    AdaptiveCardObjectModelJNI.Badge_SetBadgeStyle(swigCPtr, this, value.swigValue());
  }

  public Shape GetShape() {
    return Shape.swigToEnum(AdaptiveCardObjectModelJNI.Badge_GetShape(swigCPtr, this));
  }

  public void SetShape(Shape value) {
    AdaptiveCardObjectModelJNI.Badge_SetShape(swigCPtr, this, value.swigValue());
  }

  public BadgeSize GetBadgeSize() {
    return BadgeSize.swigToEnum(AdaptiveCardObjectModelJNI.Badge_GetBadgeSize(swigCPtr, this));
  }

  public void SetBadgeSize(BadgeSize value) {
    AdaptiveCardObjectModelJNI.Badge_SetBadgeSize(swigCPtr, this, value.swigValue());
  }

  public BadgeAppearance GetBadgeAppearance() {
    return BadgeAppearance.swigToEnum(AdaptiveCardObjectModelJNI.Badge_GetBadgeAppearance(swigCPtr, this));
  }

  public void SetBadgeAppearance(BadgeAppearance value) {
    AdaptiveCardObjectModelJNI.Badge_SetBadgeAppearance(swigCPtr, this, value.swigValue());
  }

  public IconPosition GetIconPosition() {
    return IconPosition.swigToEnum(AdaptiveCardObjectModelJNI.Badge_GetIconPosition(swigCPtr, this));
  }

  public void SetIconPosition(IconPosition value) {
    AdaptiveCardObjectModelJNI.Badge_SetIconPosition(swigCPtr, this, value.swigValue());
  }

  public static Badge dynamic_cast(BaseCardElement baseCardElement) {
    long cPtr = AdaptiveCardObjectModelJNI.Badge_dynamic_cast(BaseCardElement.getCPtr(baseCardElement), baseCardElement);
    return (cPtr == 0) ? null : new Badge(cPtr, true);
  }

}
