/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public enum BadgeSize {
  Medium,
  Large,
  ExtraLarge;

  public final int swigValue() {
    return swigValue;
  }

  public static BadgeSize swigToEnum(int swigValue) {
    BadgeSize[] swigValues = BadgeSize.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (BadgeSize swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + BadgeSize.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private BadgeSize() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private BadgeSize(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private BadgeSize(BadgeSize swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

