/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class BadgeConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BadgeConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BadgeConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(BadgeConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_BadgeConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBackgroundColor(String value) {
    AdaptiveCardObjectModelJNI.BadgeConfig_backgroundColor_set(swigCPtr, this, value);
  }

  public String getBackgroundColor() {
    return AdaptiveCardObjectModelJNI.BadgeConfig_backgroundColor_get(swigCPtr, this);
  }

  public static BadgeConfig Deserialize(JsonValue json, BadgeConfig defaultValue) {
    return new BadgeConfig(AdaptiveCardObjectModelJNI.BadgeConfig_Deserialize(JsonValue.getCPtr(json), json, BadgeConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public BadgeConfig() {
    this(AdaptiveCardObjectModelJNI.new_BadgeConfig(), true);
  }

}
