/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class Carousel extends StyledCollectionElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected Carousel(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.Carousel_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Carousel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_Carousel(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Carousel() {
    this(AdaptiveCardObjectModelJNI.new_Carousel__SWIG_0(), true);
  }

  public Carousel(CardElementType derivedType) {
    this(AdaptiveCardObjectModelJNI.new_Carousel__SWIG_1(derivedType.swigValue()), true);
  }

  public Carousel(Carousel arg0) {
    this(AdaptiveCardObjectModelJNI.new_Carousel__SWIG_2(Carousel.getCPtr(arg0), arg0), true);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.Carousel_SerializeToJsonValue(swigCPtr, this), true);
  }

  public void DeserializeChildren(ParseContext context, JsonValue value) {
    AdaptiveCardObjectModelJNI.Carousel_DeserializeChildren(swigCPtr, this, ParseContext.getCPtr(context), context, JsonValue.getCPtr(value), value);
  }

  public PageAnimation getPageAnimation() {
    return PageAnimation.swigToEnum(AdaptiveCardObjectModelJNI.Carousel_getPageAnimation(swigCPtr, this));
  }

  public void setPageAnimation(PageAnimation value) {
    AdaptiveCardObjectModelJNI.Carousel_setPageAnimation(swigCPtr, this, value.swigValue());
  }

  public CarouselPageVector GetPages() {
    return new CarouselPageVector(AdaptiveCardObjectModelJNI.Carousel_GetPages__SWIG_0(swigCPtr, this), false);
  }

  public void GetResourceInformation(RemoteResourceInformationVector resourceInfo) {
    AdaptiveCardObjectModelJNI.Carousel_GetResourceInformation(swigCPtr, this, RemoteResourceInformationVector.getCPtr(resourceInfo), resourceInfo);
  }

  public static Carousel dynamic_cast(BaseCardElement baseCardElement) {
    long cPtr = AdaptiveCardObjectModelJNI.Carousel_dynamic_cast(BaseCardElement.getCPtr(baseCardElement), baseCardElement);
    return (cPtr == 0) ? null : new Carousel(cPtr, true);
  }

}
