/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class CarouselPageVector extends java.util.AbstractList<CarouselPage> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CarouselPageVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CarouselPageVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_CarouselPageVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CarouselPageVector(CarouselPage[] initialElements) {
    this();
    reserve(initialElements.length);

    for (CarouselPage element : initialElements) {
      add(element);
    }
  }

  public CarouselPageVector(Iterable<CarouselPage> initialElements) {
    this();
    for (CarouselPage element : initialElements) {
      add(element);
    }
  }

  public CarouselPage get(int index) {
    return doGet(index);
  }

  public CarouselPage set(int index, CarouselPage e) {
    return doSet(index, e);
  }

  public boolean add(CarouselPage e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, CarouselPage e) {
    modCount++;
    doAdd(index, e);
  }

  public CarouselPage remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public CarouselPageVector() {
    this(AdaptiveCardObjectModelJNI.new_CarouselPageVector__SWIG_0(), true);
  }

  public CarouselPageVector(CarouselPageVector other) {
    this(AdaptiveCardObjectModelJNI.new_CarouselPageVector__SWIG_1(CarouselPageVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return AdaptiveCardObjectModelJNI.CarouselPageVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AdaptiveCardObjectModelJNI.CarouselPageVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AdaptiveCardObjectModelJNI.CarouselPageVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AdaptiveCardObjectModelJNI.CarouselPageVector_clear(swigCPtr, this);
  }

  public CarouselPageVector(int count, CarouselPage value) {
    this(AdaptiveCardObjectModelJNI.new_CarouselPageVector__SWIG_2(count, CarouselPage.getCPtr(value), value), true);
  }

  private int doSize() {
    return AdaptiveCardObjectModelJNI.CarouselPageVector_doSize(swigCPtr, this);
  }

  private void doAdd(CarouselPage x) {
    AdaptiveCardObjectModelJNI.CarouselPageVector_doAdd__SWIG_0(swigCPtr, this, CarouselPage.getCPtr(x), x);
  }

  private void doAdd(int index, CarouselPage x) {
    AdaptiveCardObjectModelJNI.CarouselPageVector_doAdd__SWIG_1(swigCPtr, this, index, CarouselPage.getCPtr(x), x);
  }

  private CarouselPage doRemove(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.CarouselPageVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new CarouselPage(cPtr, true);
  }

  private CarouselPage doGet(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.CarouselPageVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new CarouselPage(cPtr, true);
  }

  private CarouselPage doSet(int index, CarouselPage val) {
    long cPtr = AdaptiveCardObjectModelJNI.CarouselPageVector_doSet(swigCPtr, this, index, CarouselPage.getCPtr(val), val);
    return (cPtr == 0) ? null : new CarouselPage(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AdaptiveCardObjectModelJNI.CarouselPageVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
