/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class CitationRun extends Inline {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected CitationRun(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.CitationRun_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CitationRun obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_CitationRun(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CitationRun() {
    this(AdaptiveCardObjectModelJNI.new_CitationRun__SWIG_0(), true);
  }

  public CitationRun(CitationRun arg0) {
    this(AdaptiveCardObjectModelJNI.new_CitationRun__SWIG_1(CitationRun.getCPtr(arg0), arg0), true);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.CitationRun_SerializeToJsonValue(swigCPtr, this), true);
  }

  public int GetReferenceIndex() {
    return AdaptiveCardObjectModelJNI.CitationRun_GetReferenceIndex(swigCPtr, this);
  }

  public String GetText() {
    return AdaptiveCardObjectModelJNI.CitationRun_GetText(swigCPtr, this);
  }

  public DateTimePreparser GetTextForDateParsing() {
    return new DateTimePreparser(AdaptiveCardObjectModelJNI.CitationRun_GetTextForDateParsing(swigCPtr, this), true);
  }

  public static Inline Deserialize(ParseContext context, JsonValue root) {
    long cPtr = AdaptiveCardObjectModelJNI.CitationRun_Deserialize(ParseContext.getCPtr(context), context, JsonValue.getCPtr(root), root);
    return (cPtr == 0) ? null : new Inline(cPtr, true);
  }

  public static CitationRun dynamic_cast(Inline inlineVar) {
    long cPtr = AdaptiveCardObjectModelJNI.CitationRun_dynamic_cast(Inline.getCPtr(inlineVar), inlineVar);
    return (cPtr == 0) ? null : new CitationRun(cPtr, true);
  }

}
