/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class CitationBlock {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CitationBlock(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CitationBlock obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_CitationBlock(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTextColor(String value) {
    AdaptiveCardObjectModelJNI.CitationBlock_textColor_set(swigCPtr, this, value);
  }

  public String getTextColor() {
    return AdaptiveCardObjectModelJNI.CitationBlock_textColor_get(swigCPtr, this);
  }

  public void setBackgroundColor(String value) {
    AdaptiveCardObjectModelJNI.CitationBlock_backgroundColor_set(swigCPtr, this, value);
  }

  public String getBackgroundColor() {
    return AdaptiveCardObjectModelJNI.CitationBlock_backgroundColor_get(swigCPtr, this);
  }

  public void setBorderColor(String value) {
    AdaptiveCardObjectModelJNI.CitationBlock_borderColor_set(swigCPtr, this, value);
  }

  public String getBorderColor() {
    return AdaptiveCardObjectModelJNI.CitationBlock_borderColor_get(swigCPtr, this);
  }

  public void setBottomSheetTextColor(String value) {
    AdaptiveCardObjectModelJNI.CitationBlock_bottomSheetTextColor_set(swigCPtr, this, value);
  }

  public String getBottomSheetTextColor() {
    return AdaptiveCardObjectModelJNI.CitationBlock_bottomSheetTextColor_get(swigCPtr, this);
  }

  public void setBottomSheetKeywordsColor(String value) {
    AdaptiveCardObjectModelJNI.CitationBlock_bottomSheetKeywordsColor_set(swigCPtr, this, value);
  }

  public String getBottomSheetKeywordsColor() {
    return AdaptiveCardObjectModelJNI.CitationBlock_bottomSheetKeywordsColor_get(swigCPtr, this);
  }

  public void setBottomSheetMoreDetailColor(String value) {
    AdaptiveCardObjectModelJNI.CitationBlock_bottomSheetMoreDetailColor_set(swigCPtr, this, value);
  }

  public String getBottomSheetMoreDetailColor() {
    return AdaptiveCardObjectModelJNI.CitationBlock_bottomSheetMoreDetailColor_get(swigCPtr, this);
  }

  public void setBottomSheetBackgroundColor(String value) {
    AdaptiveCardObjectModelJNI.CitationBlock_bottomSheetBackgroundColor_set(swigCPtr, this, value);
  }

  public String getBottomSheetBackgroundColor() {
    return AdaptiveCardObjectModelJNI.CitationBlock_bottomSheetBackgroundColor_get(swigCPtr, this);
  }

  public static CitationBlock Deserialize(JsonValue json, CitationBlock defaultValue) {
    return new CitationBlock(AdaptiveCardObjectModelJNI.CitationBlock_Deserialize(JsonValue.getCPtr(json), json, CitationBlock.getCPtr(defaultValue), defaultValue), true);
  }

  public CitationBlock() {
    this(AdaptiveCardObjectModelJNI.new_CitationBlock(), true);
  }

}
