/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class CompoundButton extends BaseCardElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected CompoundButton(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.CompoundButton_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CompoundButton obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_CompoundButton(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CompoundButton() {
    this(AdaptiveCardObjectModelJNI.new_CompoundButton__SWIG_0(), true);
  }

  public CompoundButton(CompoundButton arg0) {
    this(AdaptiveCardObjectModelJNI.new_CompoundButton__SWIG_1(CompoundButton.getCPtr(arg0), arg0), true);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.CompoundButton_SerializeToJsonValue(swigCPtr, this), true);
  }

  public String getBadge() {
    return AdaptiveCardObjectModelJNI.CompoundButton_getBadge(swigCPtr, this);
  }

  public void setBadge(String value) {
    AdaptiveCardObjectModelJNI.CompoundButton_setBadge(swigCPtr, this, value);
  }

  public String getTitle() {
    return AdaptiveCardObjectModelJNI.CompoundButton_getTitle(swigCPtr, this);
  }

  public void setTitle(String value) {
    AdaptiveCardObjectModelJNI.CompoundButton_setTitle(swigCPtr, this, value);
  }

  public String getDescription() {
    return AdaptiveCardObjectModelJNI.CompoundButton_getDescription(swigCPtr, this);
  }

  public void setDescription(String value) {
    AdaptiveCardObjectModelJNI.CompoundButton_setDescription(swigCPtr, this, value);
  }

  public BaseActionElement GetSelectAction() {
    long cPtr = AdaptiveCardObjectModelJNI.CompoundButton_GetSelectAction(swigCPtr, this);
    return (cPtr == 0) ? null : new BaseActionElement(cPtr, true);
  }

  public void SetSelectAction(BaseActionElement action) {
    AdaptiveCardObjectModelJNI.CompoundButton_SetSelectAction(swigCPtr, this, BaseActionElement.getCPtr(action), action);
  }

  public IconInfo getIcon() {
    long cPtr = AdaptiveCardObjectModelJNI.CompoundButton_getIcon(swigCPtr, this);
    return (cPtr == 0) ? null : new IconInfo(cPtr, true);
  }

  public void setIcon(IconInfo value) {
    AdaptiveCardObjectModelJNI.CompoundButton_setIcon(swigCPtr, this, IconInfo.getCPtr(value), value);
  }

  public static CompoundButton dynamic_cast(BaseCardElement baseCardElement) {
    long cPtr = AdaptiveCardObjectModelJNI.CompoundButton_dynamic_cast(BaseCardElement.getCPtr(baseCardElement), baseCardElement);
    return (cPtr == 0) ? null : new CompoundButton(cPtr, true);
  }

}
