/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class ErrorMessageConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ErrorMessageConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ErrorMessageConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ErrorMessageConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_ErrorMessageConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(TextSize value) {
    AdaptiveCardObjectModelJNI.ErrorMessageConfig_size_set(swigCPtr, this, value.swigValue());
  }

  public TextSize getSize() {
    return TextSize.swigToEnum(AdaptiveCardObjectModelJNI.ErrorMessageConfig_size_get(swigCPtr, this));
  }

  public void setSpacing(Spacing value) {
    AdaptiveCardObjectModelJNI.ErrorMessageConfig_spacing_set(swigCPtr, this, value.swigValue());
  }

  public Spacing getSpacing() {
    return Spacing.swigToEnum(AdaptiveCardObjectModelJNI.ErrorMessageConfig_spacing_get(swigCPtr, this));
  }

  public void setWeight(TextWeight value) {
    AdaptiveCardObjectModelJNI.ErrorMessageConfig_weight_set(swigCPtr, this, value.swigValue());
  }

  public TextWeight getWeight() {
    return TextWeight.swigToEnum(AdaptiveCardObjectModelJNI.ErrorMessageConfig_weight_get(swigCPtr, this));
  }

  public static ErrorMessageConfig Deserialize(JsonValue json, ErrorMessageConfig defaultValue) {
    return new ErrorMessageConfig(AdaptiveCardObjectModelJNI.ErrorMessageConfig_Deserialize(JsonValue.getCPtr(json), json, ErrorMessageConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public ErrorMessageConfig() {
    this(AdaptiveCardObjectModelJNI.new_ErrorMessageConfig(), true);
  }

}
