/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class FlowLayoutVector extends java.util.AbstractList<FlowLayout> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FlowLayoutVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FlowLayoutVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_FlowLayoutVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FlowLayoutVector(FlowLayout[] initialElements) {
    this();
    reserve(initialElements.length);

    for (FlowLayout element : initialElements) {
      add(element);
    }
  }

  public FlowLayoutVector(Iterable<FlowLayout> initialElements) {
    this();
    for (FlowLayout element : initialElements) {
      add(element);
    }
  }

  public FlowLayout get(int index) {
    return doGet(index);
  }

  public FlowLayout set(int index, FlowLayout e) {
    return doSet(index, e);
  }

  public boolean add(FlowLayout e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, FlowLayout e) {
    modCount++;
    doAdd(index, e);
  }

  public FlowLayout remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public FlowLayoutVector() {
    this(AdaptiveCardObjectModelJNI.new_FlowLayoutVector__SWIG_0(), true);
  }

  public FlowLayoutVector(FlowLayoutVector other) {
    this(AdaptiveCardObjectModelJNI.new_FlowLayoutVector__SWIG_1(FlowLayoutVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return AdaptiveCardObjectModelJNI.FlowLayoutVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AdaptiveCardObjectModelJNI.FlowLayoutVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AdaptiveCardObjectModelJNI.FlowLayoutVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AdaptiveCardObjectModelJNI.FlowLayoutVector_clear(swigCPtr, this);
  }

  public FlowLayoutVector(int count, FlowLayout value) {
    this(AdaptiveCardObjectModelJNI.new_FlowLayoutVector__SWIG_2(count, FlowLayout.getCPtr(value), value), true);
  }

  private int doSize() {
    return AdaptiveCardObjectModelJNI.FlowLayoutVector_doSize(swigCPtr, this);
  }

  private void doAdd(FlowLayout x) {
    AdaptiveCardObjectModelJNI.FlowLayoutVector_doAdd__SWIG_0(swigCPtr, this, FlowLayout.getCPtr(x), x);
  }

  private void doAdd(int index, FlowLayout x) {
    AdaptiveCardObjectModelJNI.FlowLayoutVector_doAdd__SWIG_1(swigCPtr, this, index, FlowLayout.getCPtr(x), x);
  }

  private FlowLayout doRemove(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.FlowLayoutVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new FlowLayout(cPtr, true);
  }

  private FlowLayout doGet(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.FlowLayoutVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new FlowLayout(cPtr, true);
  }

  private FlowLayout doSet(int index, FlowLayout val) {
    long cPtr = AdaptiveCardObjectModelJNI.FlowLayoutVector_doSet(swigCPtr, this, index, FlowLayout.getCPtr(val), val);
    return (cPtr == 0) ? null : new FlowLayout(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AdaptiveCardObjectModelJNI.FlowLayoutVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
