/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class GridAreaVector extends java.util.AbstractList<GridArea> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GridAreaVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GridAreaVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GridAreaVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_GridAreaVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GridAreaVector(GridArea[] initialElements) {
    this();
    reserve(initialElements.length);

    for (GridArea element : initialElements) {
      add(element);
    }
  }

  public GridAreaVector(Iterable<GridArea> initialElements) {
    this();
    for (GridArea element : initialElements) {
      add(element);
    }
  }

  public GridArea get(int index) {
    return doGet(index);
  }

  public GridArea set(int index, GridArea e) {
    return doSet(index, e);
  }

  public boolean add(GridArea e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, GridArea e) {
    modCount++;
    doAdd(index, e);
  }

  public GridArea remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public GridAreaVector() {
    this(AdaptiveCardObjectModelJNI.new_GridAreaVector__SWIG_0(), true);
  }

  public GridAreaVector(GridAreaVector other) {
    this(AdaptiveCardObjectModelJNI.new_GridAreaVector__SWIG_1(GridAreaVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return AdaptiveCardObjectModelJNI.GridAreaVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AdaptiveCardObjectModelJNI.GridAreaVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AdaptiveCardObjectModelJNI.GridAreaVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AdaptiveCardObjectModelJNI.GridAreaVector_clear(swigCPtr, this);
  }

  public GridAreaVector(int count, GridArea value) {
    this(AdaptiveCardObjectModelJNI.new_GridAreaVector__SWIG_2(count, GridArea.getCPtr(value), value), true);
  }

  private int doSize() {
    return AdaptiveCardObjectModelJNI.GridAreaVector_doSize(swigCPtr, this);
  }

  private void doAdd(GridArea x) {
    AdaptiveCardObjectModelJNI.GridAreaVector_doAdd__SWIG_0(swigCPtr, this, GridArea.getCPtr(x), x);
  }

  private void doAdd(int index, GridArea x) {
    AdaptiveCardObjectModelJNI.GridAreaVector_doAdd__SWIG_1(swigCPtr, this, index, GridArea.getCPtr(x), x);
  }

  private GridArea doRemove(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.GridAreaVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new GridArea(cPtr, true);
  }

  private GridArea doGet(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.GridAreaVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new GridArea(cPtr, true);
  }

  private GridArea doSet(int index, GridArea val) {
    long cPtr = AdaptiveCardObjectModelJNI.GridAreaVector_doSet(swigCPtr, this, index, GridArea.getCPtr(val), val);
    return (cPtr == 0) ? null : new GridArea(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AdaptiveCardObjectModelJNI.GridAreaVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
