/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public enum HostWidthType {
  Default(0),
  VeryNarrow(1),
  Narrow(2),
  Standard(3),
  Wide(4);

  public final int swigValue() {
    return swigValue;
  }

  public static HostWidthType swigToEnum(int swigValue) {
    HostWidthType[] swigValues = HostWidthType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (HostWidthType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + HostWidthType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private HostWidthType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private HostWidthType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private HostWidthType(HostWidthType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

