/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class IconsConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IconsConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IconsConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_IconsConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIconSize(long value) {
    AdaptiveCardObjectModelJNI.IconsConfig_iconSize_set(swigCPtr, this, value);
  }

  public long getIconSize() {
    return AdaptiveCardObjectModelJNI.IconsConfig_iconSize_get(swigCPtr, this);
  }

  public void setIconPadding(long value) {
    AdaptiveCardObjectModelJNI.IconsConfig_iconPadding_set(swigCPtr, this, value);
  }

  public long getIconPadding() {
    return AdaptiveCardObjectModelJNI.IconsConfig_iconPadding_get(swigCPtr, this);
  }

  public static IconsConfig Deserialize(JsonValue json, IconsConfig defaultValue) {
    return new IconsConfig(AdaptiveCardObjectModelJNI.IconsConfig_Deserialize(JsonValue.getCPtr(json), json, IconsConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public IconsConfig() {
    this(AdaptiveCardObjectModelJNI.new_IconsConfig(), true);
  }

}
