/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class Icon extends BaseCardElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected Icon(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.Icon_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Icon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_Icon(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Icon() {
    this(AdaptiveCardObjectModelJNI.new_Icon__SWIG_0(), true);
  }

  public Icon(Icon arg0) {
    this(AdaptiveCardObjectModelJNI.new_Icon__SWIG_1(Icon.getCPtr(arg0), arg0), true);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.Icon_SerializeToJsonValue(swigCPtr, this), true);
  }

  public ForegroundColor getForgroundColor() {
    return ForegroundColor.swigToEnum(AdaptiveCardObjectModelJNI.Icon_getForgroundColor(swigCPtr, this));
  }

  public void setForgroundColor(ForegroundColor value) {
    AdaptiveCardObjectModelJNI.Icon_setForgroundColor(swigCPtr, this, value.swigValue());
  }

  public IconSize getIconSize() {
    return IconSize.swigToEnum(AdaptiveCardObjectModelJNI.Icon_getIconSize(swigCPtr, this));
  }

  public void setIconSize(IconSize value) {
    AdaptiveCardObjectModelJNI.Icon_setIconSize(swigCPtr, this, value.swigValue());
  }

  public IconStyle getIconStyle() {
    return IconStyle.swigToEnum(AdaptiveCardObjectModelJNI.Icon_getIconStyle(swigCPtr, this));
  }

  public void setIconStyle(IconStyle value) {
    AdaptiveCardObjectModelJNI.Icon_setIconStyle(swigCPtr, this, value.swigValue());
  }

  public String GetName() {
    return AdaptiveCardObjectModelJNI.Icon_GetName(swigCPtr, this);
  }

  public void SetName(String value) {
    AdaptiveCardObjectModelJNI.Icon_SetName(swigCPtr, this, value);
  }

  public BaseActionElement GetSelectAction() {
    long cPtr = AdaptiveCardObjectModelJNI.Icon_GetSelectAction(swigCPtr, this);
    return (cPtr == 0) ? null : new BaseActionElement(cPtr, true);
  }

  public void SetSelectAction(BaseActionElement action) {
    AdaptiveCardObjectModelJNI.Icon_SetSelectAction(swigCPtr, this, BaseActionElement.getCPtr(action), action);
  }

  public long getSize() {
    return AdaptiveCardObjectModelJNI.Icon_getSize(swigCPtr, this);
  }

  public String getStyle() {
    return AdaptiveCardObjectModelJNI.Icon_getStyle(swigCPtr, this);
  }

  public String GetSVGResourceURL() {
    return AdaptiveCardObjectModelJNI.Icon_GetSVGResourceURL(swigCPtr, this);
  }

  public void GetResourceInformation(RemoteResourceInformationVector resourceInfo) {
    AdaptiveCardObjectModelJNI.Icon_GetResourceInformation(swigCPtr, this, RemoteResourceInformationVector.getCPtr(resourceInfo), resourceInfo);
  }

  public static Icon dynamic_cast(BaseCardElement baseCardElement) {
    long cPtr = AdaptiveCardObjectModelJNI.Icon_dynamic_cast(BaseCardElement.getCPtr(baseCardElement), baseCardElement);
    return (cPtr == 0) ? null : new Icon(cPtr, true);
  }

}
