/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class ImageConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImageConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ImageConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_ImageConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setImageSize(ImageSize value) {
    AdaptiveCardObjectModelJNI.ImageConfig_imageSize_set(swigCPtr, this, value.swigValue());
  }

  public ImageSize getImageSize() {
    return ImageSize.swigToEnum(AdaptiveCardObjectModelJNI.ImageConfig_imageSize_get(swigCPtr, this));
  }

  public static ImageConfig Deserialize(JsonValue json, ImageConfig defaultValue) {
    return new ImageConfig(AdaptiveCardObjectModelJNI.ImageConfig_Deserialize(JsonValue.getCPtr(json), json, ImageConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public ImageConfig() {
    this(AdaptiveCardObjectModelJNI.new_ImageConfig(), true);
  }

}
