/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class InternalId {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InternalId(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InternalId obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(InternalId obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_InternalId(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public InternalId() {
    this(AdaptiveCardObjectModelJNI.new_InternalId(), true);
  }

  public static InternalId Next() {
    return new InternalId(AdaptiveCardObjectModelJNI.InternalId_Next(), true);
  }

  public static InternalId Current() {
    return new InternalId(AdaptiveCardObjectModelJNI.InternalId_Current(), true);
  }

  public long Hash() {
    return AdaptiveCardObjectModelJNI.InternalId_Hash(swigCPtr, this);
  }

  public final static long Invalid = 0;
}
