/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public enum LayoutContainerType {
  None(0),
  Stack,
  Flow,
  AreaGrid;

  public final int swigValue() {
    return swigValue;
  }

  public static LayoutContainerType swigToEnum(int swigValue) {
    LayoutContainerType[] swigValues = LayoutContainerType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (LayoutContainerType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + LayoutContainerType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private LayoutContainerType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private LayoutContainerType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private LayoutContainerType(LayoutContainerType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

