/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class LayoutVector extends java.util.AbstractList<Layout> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LayoutVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LayoutVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(LayoutVector obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_LayoutVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LayoutVector(Layout[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Layout element : initialElements) {
      add(element);
    }
  }

  public LayoutVector(Iterable<Layout> initialElements) {
    this();
    for (Layout element : initialElements) {
      add(element);
    }
  }

  public Layout get(int index) {
    return doGet(index);
  }

  public Layout set(int index, Layout e) {
    return doSet(index, e);
  }

  public boolean add(Layout e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Layout e) {
    modCount++;
    doAdd(index, e);
  }

  public Layout remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public LayoutVector() {
    this(AdaptiveCardObjectModelJNI.new_LayoutVector__SWIG_0(), true);
  }

  public LayoutVector(LayoutVector other) {
    this(AdaptiveCardObjectModelJNI.new_LayoutVector__SWIG_1(LayoutVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return AdaptiveCardObjectModelJNI.LayoutVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AdaptiveCardObjectModelJNI.LayoutVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AdaptiveCardObjectModelJNI.LayoutVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AdaptiveCardObjectModelJNI.LayoutVector_clear(swigCPtr, this);
  }

  public LayoutVector(int count, Layout value) {
    this(AdaptiveCardObjectModelJNI.new_LayoutVector__SWIG_2(count, Layout.getCPtr(value), value), true);
  }

  private int doSize() {
    return AdaptiveCardObjectModelJNI.LayoutVector_doSize(swigCPtr, this);
  }

  private void doAdd(Layout x) {
    AdaptiveCardObjectModelJNI.LayoutVector_doAdd__SWIG_0(swigCPtr, this, Layout.getCPtr(x), x);
  }

  private void doAdd(int index, Layout x) {
    AdaptiveCardObjectModelJNI.LayoutVector_doAdd__SWIG_1(swigCPtr, this, index, Layout.getCPtr(x), x);
  }

  private Layout doRemove(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.LayoutVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Layout(cPtr, true);
  }

  private Layout doGet(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.LayoutVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Layout(cPtr, true);
  }

  private Layout doSet(int index, Layout val) {
    long cPtr = AdaptiveCardObjectModelJNI.LayoutVector_doSet(swigCPtr, this, index, Layout.getCPtr(val), val);
    return (cPtr == 0) ? null : new Layout(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AdaptiveCardObjectModelJNI.LayoutVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
