/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class MarkDownParser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MarkDownParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MarkDownParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MarkDownParser obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_MarkDownParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MarkDownParser(String txt) {
    this(AdaptiveCardObjectModelJNI.new_MarkDownParser(txt), true);
  }

  public String TransformToHtml() {
    return AdaptiveCardObjectModelJNI.MarkDownParser_TransformToHtml(swigCPtr, this);
  }

  public String GetRawText() {
    return AdaptiveCardObjectModelJNI.MarkDownParser_GetRawText(swigCPtr, this);
  }

  public boolean HasHtmlTags() {
    return AdaptiveCardObjectModelJNI.MarkDownParser_HasHtmlTags(swigCPtr, this);
  }

  public boolean IsEscaped() {
    return AdaptiveCardObjectModelJNI.MarkDownParser_IsEscaped(swigCPtr, this);
  }

}
