/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class MediaConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MediaConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MediaConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(MediaConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_MediaConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDefaultPoster(String value) {
    AdaptiveCardObjectModelJNI.MediaConfig_defaultPoster_set(swigCPtr, this, value);
  }

  public String getDefaultPoster() {
    return AdaptiveCardObjectModelJNI.MediaConfig_defaultPoster_get(swigCPtr, this);
  }

  public void setPlayButton(String value) {
    AdaptiveCardObjectModelJNI.MediaConfig_playButton_set(swigCPtr, this, value);
  }

  public String getPlayButton() {
    return AdaptiveCardObjectModelJNI.MediaConfig_playButton_get(swigCPtr, this);
  }

  public void setAllowInlinePlayback(boolean value) {
    AdaptiveCardObjectModelJNI.MediaConfig_allowInlinePlayback_set(swigCPtr, this, value);
  }

  public boolean getAllowInlinePlayback() {
    return AdaptiveCardObjectModelJNI.MediaConfig_allowInlinePlayback_get(swigCPtr, this);
  }

  public static MediaConfig Deserialize(JsonValue json, MediaConfig defaultValue) {
    return new MediaConfig(AdaptiveCardObjectModelJNI.MediaConfig_Deserialize(JsonValue.getCPtr(json), json, MediaConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public MediaConfig() {
    this(AdaptiveCardObjectModelJNI.new_MediaConfig(), true);
  }

}
