/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class PageControlConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PageControlConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PageControlConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_PageControlConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSelectedTintColor(String value) {
    AdaptiveCardObjectModelJNI.PageControlConfig_selectedTintColor_set(swigCPtr, this, value);
  }

  public String getSelectedTintColor() {
    return AdaptiveCardObjectModelJNI.PageControlConfig_selectedTintColor_get(swigCPtr, this);
  }

  public void setUnselectedTintColor(String value) {
    AdaptiveCardObjectModelJNI.PageControlConfig_unselectedTintColor_set(swigCPtr, this, value);
  }

  public String getUnselectedTintColor() {
    return AdaptiveCardObjectModelJNI.PageControlConfig_unselectedTintColor_get(swigCPtr, this);
  }

  public static PageControlConfig Deserialize(JsonValue json, PageControlConfig defaultValue) {
    return new PageControlConfig(AdaptiveCardObjectModelJNI.PageControlConfig_Deserialize(JsonValue.getCPtr(json), json, PageControlConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public PageControlConfig() {
    this(AdaptiveCardObjectModelJNI.new_PageControlConfig(), true);
  }

}
