/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public enum PageAnimation {
  Slide(0),
  CrossFade,
  None;

  public final int swigValue() {
    return swigValue;
  }

  public static PageAnimation swigToEnum(int swigValue) {
    PageAnimation[] swigValues = PageAnimation.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (PageAnimation swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + PageAnimation.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private PageAnimation() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private PageAnimation(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private PageAnimation(PageAnimation swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

