/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class PopoverAction extends BaseActionElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected PopoverAction(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.PopoverAction_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PopoverAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_PopoverAction(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PopoverAction() {
    this(AdaptiveCardObjectModelJNI.new_PopoverAction__SWIG_0(), true);
  }

  public PopoverAction(PopoverAction arg0) {
    this(AdaptiveCardObjectModelJNI.new_PopoverAction__SWIG_1(PopoverAction.getCPtr(arg0), arg0), true);
  }

  public PopoverAction(BaseCardElement content, boolean displayArrow, String maxPopoverWidth) {
    this(AdaptiveCardObjectModelJNI.new_PopoverAction__SWIG_3(BaseCardElement.getCPtr(content), content, displayArrow, maxPopoverWidth), true);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.PopoverAction_SerializeToJsonValue(swigCPtr, this), true);
  }

  public boolean GetDisplayArrow() {
    return AdaptiveCardObjectModelJNI.PopoverAction_GetDisplayArrow(swigCPtr, this);
  }

  public String GetMaxPopoverWidth() {
    return AdaptiveCardObjectModelJNI.PopoverAction_GetMaxPopoverWidth(swigCPtr, this);
  }

  public LabelPosition GetPosition() {
    return LabelPosition.swigToEnum(AdaptiveCardObjectModelJNI.PopoverAction_GetPosition(swigCPtr, this));
  }

  public BaseCardElement GetContent() {
    long cPtr = AdaptiveCardObjectModelJNI.PopoverAction_GetContent(swigCPtr, this);
    return (cPtr == 0) ? null : new BaseCardElement(cPtr, true);
  }

  public static PopoverAction dynamic_cast(BaseActionElement baseActionElement) {
    long cPtr = AdaptiveCardObjectModelJNI.PopoverAction_dynamic_cast(BaseActionElement.getCPtr(baseActionElement), baseActionElement);
    return (cPtr == 0) ? null : new PopoverAction(cPtr, true);
  }

}
