/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class PopoverConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PopoverConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PopoverConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_PopoverConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBackgroundColor(String value) {
    AdaptiveCardObjectModelJNI.PopoverConfig_backgroundColor_set(swigCPtr, this, value);
  }

  public String getBackgroundColor() {
    return AdaptiveCardObjectModelJNI.PopoverConfig_backgroundColor_get(swigCPtr, this);
  }

  public static PopoverConfig Deserialize(JsonValue json, PopoverConfig defaultValue) {
    return new PopoverConfig(AdaptiveCardObjectModelJNI.PopoverConfig_Deserialize(JsonValue.getCPtr(json), json, PopoverConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public PopoverConfig() {
    this(AdaptiveCardObjectModelJNI.new_PopoverConfig(), true);
  }

}
