/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class ProgressRing extends BaseCardElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ProgressRing(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.ProgressRing_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProgressRing obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_ProgressRing(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ProgressRing() {
    this(AdaptiveCardObjectModelJNI.new_ProgressRing__SWIG_0(), true);
  }

  public ProgressRing(ProgressRing arg0) {
    this(AdaptiveCardObjectModelJNI.new_ProgressRing__SWIG_1(ProgressRing.getCPtr(arg0), arg0), true);
  }

  public String GetLabel() {
    return AdaptiveCardObjectModelJNI.ProgressRing_GetLabel(swigCPtr, this);
  }

  public LabelPosition GetLabelPosition() {
    return LabelPosition.swigToEnum(AdaptiveCardObjectModelJNI.ProgressRing_GetLabelPosition(swigCPtr, this));
  }

  public ProgressSize GetSize() {
    return ProgressSize.swigToEnum(AdaptiveCardObjectModelJNI.ProgressRing_GetSize(swigCPtr, this));
  }

  public @androidx.annotation.Nullable HorizontalAlignment GetHorizontalAlignment() {
    StdOptionalHorizontalAlignment optvalue = new StdOptionalHorizontalAlignment(AdaptiveCardObjectModelJNI.ProgressRing_GetHorizontalAlignment(swigCPtr, this), false);
    return optvalue.has_value() ? optvalue.value() : null;
  }

  public ProgressRing(ProgressSize progressSize, LabelPosition labelPosition, String label, HorizontalAlignment horizontalAlignment) {
    this(AdaptiveCardObjectModelJNI.new_ProgressRing__SWIG_3(progressSize.swigValue(), labelPosition.swigValue(), label, horizontalAlignment.swigValue()), true);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.ProgressRing_SerializeToJsonValue(swigCPtr, this), true);
  }

  public static ProgressRing dynamic_cast(BaseCardElement baseCardElement) {
    long cPtr = AdaptiveCardObjectModelJNI.ProgressRing_dynamic_cast(BaseCardElement.getCPtr(baseCardElement), baseCardElement);
    return (cPtr == 0) ? null : new ProgressRing(cPtr, true);
  }

}
