/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class ProgressBar extends BaseCardElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected ProgressBar(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.ProgressBar_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProgressBar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_ProgressBar(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ProgressBar() {
    this(AdaptiveCardObjectModelJNI.new_ProgressBar__SWIG_0(), true);
  }

  public ProgressBar(ProgressBar arg0) {
    this(AdaptiveCardObjectModelJNI.new_ProgressBar__SWIG_1(ProgressBar.getCPtr(arg0), arg0), true);
  }

  public ProgressBar(ProgressBarColor color, float max, float value) {
    this(AdaptiveCardObjectModelJNI.new_ProgressBar__SWIG_3(color.swigValue(), max, value), true);
  }

  public ProgressBarColor GetColor() {
    return ProgressBarColor.swigToEnum(AdaptiveCardObjectModelJNI.ProgressBar_GetColor__SWIG_0(swigCPtr, this));
  }

  public double GetMax() {
    return AdaptiveCardObjectModelJNI.ProgressBar_GetMax__SWIG_0(swigCPtr, this);
  }

  public @androidx.annotation.Nullable Double GetValue() {
    StdOptionalDouble optvalue = new StdOptionalDouble(AdaptiveCardObjectModelJNI.ProgressBar_GetValue__SWIG_0(swigCPtr, this), false);
    return optvalue.has_value() ? optvalue.value() : null;
  }

  public HorizontalAlignment GetHorizontalAlignment() {
    return HorizontalAlignment.swigToEnum(AdaptiveCardObjectModelJNI.ProgressBar_GetHorizontalAlignment(swigCPtr, this));
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.ProgressBar_SerializeToJsonValue(swigCPtr, this), true);
  }

  public static ProgressBar dynamic_cast(BaseCardElement baseCardElement) {
    long cPtr = AdaptiveCardObjectModelJNI.ProgressBar_dynamic_cast(BaseCardElement.getCPtr(baseCardElement), baseCardElement);
    return (cPtr == 0) ? null : new ProgressBar(cPtr, true);
  }

}
