/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class RatingLabelVector extends java.util.AbstractList<RatingLabel> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RatingLabelVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RatingLabelVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_RatingLabelVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RatingLabelVector(RatingLabel[] initialElements) {
    this();
    reserve(initialElements.length);

    for (RatingLabel element : initialElements) {
      add(element);
    }
  }

  public RatingLabelVector(Iterable<RatingLabel> initialElements) {
    this();
    for (RatingLabel element : initialElements) {
      add(element);
    }
  }

  public RatingLabel get(int index) {
    return doGet(index);
  }

  public RatingLabel set(int index, RatingLabel e) {
    return doSet(index, e);
  }

  public boolean add(RatingLabel e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, RatingLabel e) {
    modCount++;
    doAdd(index, e);
  }

  public RatingLabel remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public RatingLabelVector() {
    this(AdaptiveCardObjectModelJNI.new_RatingLabelVector__SWIG_0(), true);
  }

  public RatingLabelVector(RatingLabelVector other) {
    this(AdaptiveCardObjectModelJNI.new_RatingLabelVector__SWIG_1(RatingLabelVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return AdaptiveCardObjectModelJNI.RatingLabelVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AdaptiveCardObjectModelJNI.RatingLabelVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AdaptiveCardObjectModelJNI.RatingLabelVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AdaptiveCardObjectModelJNI.RatingLabelVector_clear(swigCPtr, this);
  }

  public RatingLabelVector(int count, RatingLabel value) {
    this(AdaptiveCardObjectModelJNI.new_RatingLabelVector__SWIG_2(count, RatingLabel.getCPtr(value), value), true);
  }

  private int doSize() {
    return AdaptiveCardObjectModelJNI.RatingLabelVector_doSize(swigCPtr, this);
  }

  private void doAdd(RatingLabel x) {
    AdaptiveCardObjectModelJNI.RatingLabelVector_doAdd__SWIG_0(swigCPtr, this, RatingLabel.getCPtr(x), x);
  }

  private void doAdd(int index, RatingLabel x) {
    AdaptiveCardObjectModelJNI.RatingLabelVector_doAdd__SWIG_1(swigCPtr, this, index, RatingLabel.getCPtr(x), x);
  }

  private RatingLabel doRemove(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.RatingLabelVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new RatingLabel(cPtr, true);
  }

  private RatingLabel doGet(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.RatingLabelVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new RatingLabel(cPtr, true);
  }

  private RatingLabel doSet(int index, RatingLabel val) {
    long cPtr = AdaptiveCardObjectModelJNI.RatingLabelVector_doSet(swigCPtr, this, index, RatingLabel.getCPtr(val), val);
    return (cPtr == 0) ? null : new RatingLabel(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AdaptiveCardObjectModelJNI.RatingLabelVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
