/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class RatingInput extends BaseInputElement {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected RatingInput(long cPtr, boolean cMemoryOwn) {
    super(AdaptiveCardObjectModelJNI.RatingInput_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RatingInput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        AdaptiveCardObjectModelJNI.delete_RatingInput(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RatingInput() {
    this(AdaptiveCardObjectModelJNI.new_RatingInput__SWIG_0(), true);
  }

  public RatingInput(RatingInput arg0) {
    this(AdaptiveCardObjectModelJNI.new_RatingInput__SWIG_1(RatingInput.getCPtr(arg0), arg0), true);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.RatingInput_SerializeToJsonValue(swigCPtr, this), true);
  }

  public @androidx.annotation.Nullable HorizontalAlignment GetHorizontalAlignment() {
    StdOptionalHorizontalAlignment optvalue = new StdOptionalHorizontalAlignment(AdaptiveCardObjectModelJNI.RatingInput_GetHorizontalAlignment(swigCPtr, this), false);
    return optvalue.has_value() ? optvalue.value() : null;
  }

  public void SetHorizontalAlignment(@androidx.annotation.Nullable HorizontalAlignment value) {
    StdOptionalHorizontalAlignment optvalue = (value == null) ? new StdOptionalHorizontalAlignment() : new StdOptionalHorizontalAlignment(value);
    {
      AdaptiveCardObjectModelJNI.RatingInput_SetHorizontalAlignment(swigCPtr, this, StdOptionalHorizontalAlignment.getCPtr(optvalue), optvalue);
    }
  }

  public double GetValue() {
    return AdaptiveCardObjectModelJNI.RatingInput_GetValue(swigCPtr, this);
  }

  public void SetValue(double value) {
    AdaptiveCardObjectModelJNI.RatingInput_SetValue(swigCPtr, this, value);
  }

  public double GetMax() {
    return AdaptiveCardObjectModelJNI.RatingInput_GetMax(swigCPtr, this);
  }

  public void SetMax(double value) {
    AdaptiveCardObjectModelJNI.RatingInput_SetMax(swigCPtr, this, value);
  }

  public RatingSize GetRatingSize() {
    return RatingSize.swigToEnum(AdaptiveCardObjectModelJNI.RatingInput_GetRatingSize(swigCPtr, this));
  }

  public void SetRatingSize(RatingSize value) {
    AdaptiveCardObjectModelJNI.RatingInput_SetRatingSize(swigCPtr, this, value.swigValue());
  }

  public RatingColor GetRatingColor() {
    return RatingColor.swigToEnum(AdaptiveCardObjectModelJNI.RatingInput_GetRatingColor(swigCPtr, this));
  }

  public void SetRatingColor(RatingColor value) {
    AdaptiveCardObjectModelJNI.RatingInput_SetRatingColor(swigCPtr, this, value.swigValue());
  }

  public static RatingInput dynamic_cast(BaseCardElement baseCardElement) {
    long cPtr = AdaptiveCardObjectModelJNI.RatingInput_dynamic_cast(BaseCardElement.getCPtr(baseCardElement), baseCardElement);
    return (cPtr == 0) ? null : new RatingInput(cPtr, true);
  }

}
