/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class RatingStarCofig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RatingStarCofig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RatingStarCofig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(RatingStarCofig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_RatingStarCofig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMarigoldColor(String value) {
    AdaptiveCardObjectModelJNI.RatingStarCofig_marigoldColor_set(swigCPtr, this, value);
  }

  public String getMarigoldColor() {
    return AdaptiveCardObjectModelJNI.RatingStarCofig_marigoldColor_get(swigCPtr, this);
  }

  public void setNeutralColor(String value) {
    AdaptiveCardObjectModelJNI.RatingStarCofig_neutralColor_set(swigCPtr, this, value);
  }

  public String getNeutralColor() {
    return AdaptiveCardObjectModelJNI.RatingStarCofig_neutralColor_get(swigCPtr, this);
  }

  public static RatingStarCofig Deserialize(JsonValue json, RatingStarCofig defaultValue) {
    return new RatingStarCofig(AdaptiveCardObjectModelJNI.RatingStarCofig_Deserialize(JsonValue.getCPtr(json), json, RatingStarCofig.getCPtr(defaultValue), defaultValue), true);
  }

  public RatingStarCofig() {
    this(AdaptiveCardObjectModelJNI.new_RatingStarCofig(), true);
  }

}
