/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class RatingInputVector extends java.util.AbstractList<RatingInput> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RatingInputVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RatingInputVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_RatingInputVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RatingInputVector(RatingInput[] initialElements) {
    this();
    reserve(initialElements.length);

    for (RatingInput element : initialElements) {
      add(element);
    }
  }

  public RatingInputVector(Iterable<RatingInput> initialElements) {
    this();
    for (RatingInput element : initialElements) {
      add(element);
    }
  }

  public RatingInput get(int index) {
    return doGet(index);
  }

  public RatingInput set(int index, RatingInput e) {
    return doSet(index, e);
  }

  public boolean add(RatingInput e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, RatingInput e) {
    modCount++;
    doAdd(index, e);
  }

  public RatingInput remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public RatingInputVector() {
    this(AdaptiveCardObjectModelJNI.new_RatingInputVector__SWIG_0(), true);
  }

  public RatingInputVector(RatingInputVector other) {
    this(AdaptiveCardObjectModelJNI.new_RatingInputVector__SWIG_1(RatingInputVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return AdaptiveCardObjectModelJNI.RatingInputVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AdaptiveCardObjectModelJNI.RatingInputVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AdaptiveCardObjectModelJNI.RatingInputVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AdaptiveCardObjectModelJNI.RatingInputVector_clear(swigCPtr, this);
  }

  public RatingInputVector(int count, RatingInput value) {
    this(AdaptiveCardObjectModelJNI.new_RatingInputVector__SWIG_2(count, RatingInput.getCPtr(value), value), true);
  }

  private int doSize() {
    return AdaptiveCardObjectModelJNI.RatingInputVector_doSize(swigCPtr, this);
  }

  private void doAdd(RatingInput x) {
    AdaptiveCardObjectModelJNI.RatingInputVector_doAdd__SWIG_0(swigCPtr, this, RatingInput.getCPtr(x), x);
  }

  private void doAdd(int index, RatingInput x) {
    AdaptiveCardObjectModelJNI.RatingInputVector_doAdd__SWIG_1(swigCPtr, this, index, RatingInput.getCPtr(x), x);
  }

  private RatingInput doRemove(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.RatingInputVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new RatingInput(cPtr, true);
  }

  private RatingInput doGet(int index) {
    long cPtr = AdaptiveCardObjectModelJNI.RatingInputVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new RatingInput(cPtr, true);
  }

  private RatingInput doSet(int index, RatingInput val) {
    long cPtr = AdaptiveCardObjectModelJNI.RatingInputVector_doSet(swigCPtr, this, index, RatingInput.getCPtr(val), val);
    return (cPtr == 0) ? null : new RatingInput(cPtr, true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    AdaptiveCardObjectModelJNI.RatingInputVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
