/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public enum ReferenceIcon {
  AdobeIllustrator,
  AdobePhotoshop,
  AdobeInDesign,
  AdobeFlash,
  MsWord,
  MsExcel,
  MsPowerPoint,
  MsOneNote,
  MsSharePoint,
  MsVisio,
  MsLoop,
  MsWhiteboard,
  Code,
  Gif,
  Image,
  Pdf,
  Sketch,
  Sound,
  Text,
  Video,
  Zip;

  public final int swigValue() {
    return swigValue;
  }

  public static ReferenceIcon swigToEnum(int swigValue) {
    ReferenceIcon[] swigValues = ReferenceIcon.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ReferenceIcon swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ReferenceIcon.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ReferenceIcon() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ReferenceIcon(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ReferenceIcon(ReferenceIcon swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

