/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class References {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected References(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(References obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_References(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public References() {
    this(AdaptiveCardObjectModelJNI.new_References__SWIG_0(), true);
  }

  public References(ReferenceType type, String _abstract, String title, String url, StringVector keywords) {
    this(AdaptiveCardObjectModelJNI.new_References__SWIG_1(type.swigValue(), _abstract, title, url, StringVector.getCPtr(keywords), keywords), true);
  }

  public References(ReferenceType type, String _abstract, String title, String url, StringVector keywords, AdaptiveCard content) {
    this(AdaptiveCardObjectModelJNI.new_References__SWIG_2(type.swigValue(), _abstract, title, url, StringVector.getCPtr(keywords), keywords, AdaptiveCard.getCPtr(content), content), true);
  }

  public boolean ShouldSerialize() {
    return AdaptiveCardObjectModelJNI.References_ShouldSerialize(swigCPtr, this);
  }

  public String Serialize() {
    return AdaptiveCardObjectModelJNI.References_Serialize(swigCPtr, this);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.References_SerializeToJsonValue(swigCPtr, this), true);
  }

  public ReferenceType GetType() {
    return ReferenceType.swigToEnum(AdaptiveCardObjectModelJNI.References_GetType(swigCPtr, this));
  }

  public String GetAbstract() {
    return AdaptiveCardObjectModelJNI.References_GetAbstract(swigCPtr, this);
  }

  public String GetTitle() {
    return AdaptiveCardObjectModelJNI.References_GetTitle(swigCPtr, this);
  }

  public String GetUrl() {
    return AdaptiveCardObjectModelJNI.References_GetUrl(swigCPtr, this);
  }

  public StringVector GetKeywords() {
    return new StringVector(AdaptiveCardObjectModelJNI.References_GetKeywords(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__optionalT_std__shared_ptrT_AdaptiveCards__AdaptiveCard_t_t GetContent() {
    return new SWIGTYPE_p_std__optionalT_std__shared_ptrT_AdaptiveCards__AdaptiveCard_t_t(AdaptiveCardObjectModelJNI.References_GetContent(swigCPtr, this), true);
  }

  public static References Deserialize(ParseContext context, JsonValue json) {
    long cPtr = AdaptiveCardObjectModelJNI.References_Deserialize(ParseContext.getCPtr(context), context, JsonValue.getCPtr(json), json);
    return (cPtr == 0) ? null : new References(cPtr, true);
  }

  public static References DeserializeFromString(ParseContext context, String jsonString) {
    long cPtr = AdaptiveCardObjectModelJNI.References_DeserializeFromString(ParseContext.getCPtr(context), context, jsonString);
    return (cPtr == 0) ? null : new References(cPtr, true);
  }

}
