/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class Resources {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected Resources(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Resources obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_Resources(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Resources() {
    this(AdaptiveCardObjectModelJNI.new_Resources__SWIG_0(), true);
  }

  public Resources(SWIGTYPE_p_std__unordered_mapT_std__string_std__shared_ptrT_AdaptiveCards__StringResource_t_t strings) {
    this(AdaptiveCardObjectModelJNI.new_Resources__SWIG_1(SWIGTYPE_p_std__unordered_mapT_std__string_std__shared_ptrT_AdaptiveCards__StringResource_t_t.getCPtr(strings)), true);
  }

  public boolean ShouldSerialize() {
    return AdaptiveCardObjectModelJNI.Resources_ShouldSerialize(swigCPtr, this);
  }

  public String Serialize() {
    return AdaptiveCardObjectModelJNI.Resources_Serialize(swigCPtr, this);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.Resources_SerializeToJsonValue(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__unordered_mapT_std__string_std__shared_ptrT_AdaptiveCards__StringResource_t_t GetStrings() {
    return new SWIGTYPE_p_std__unordered_mapT_std__string_std__shared_ptrT_AdaptiveCards__StringResource_t_t(AdaptiveCardObjectModelJNI.Resources_GetStrings(swigCPtr, this), true);
  }

  public static Resources Deserialize(ParseContext context, JsonValue json) {
    long cPtr = AdaptiveCardObjectModelJNI.Resources_Deserialize(ParseContext.getCPtr(context), context, JsonValue.getCPtr(json), json);
    return (cPtr == 0) ? null : new Resources(cPtr, true);
  }

  public static Resources DeserializeFromString(ParseContext context, String jsonString) {
    long cPtr = AdaptiveCardObjectModelJNI.Resources_DeserializeFromString(ParseContext.getCPtr(context), context, jsonString);
    return (cPtr == 0) ? null : new Resources(cPtr, true);
  }

}
