/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class StdOptionalTextSize {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StdOptionalTextSize(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StdOptionalTextSize obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StdOptionalTextSize obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_StdOptionalTextSize(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StdOptionalTextSize() {
    this(AdaptiveCardObjectModelJNI.new_StdOptionalTextSize__SWIG_0(), true);
  }

  public StdOptionalTextSize(TextSize arg0) {
    this(AdaptiveCardObjectModelJNI.new_StdOptionalTextSize__SWIG_1(arg0.swigValue()), true);
  }

  public boolean has_value() {
    return AdaptiveCardObjectModelJNI.StdOptionalTextSize_has_value(swigCPtr, this);
  }

  public TextSize value() {
    return TextSize.swigToEnum(AdaptiveCardObjectModelJNI.StdOptionalTextSize_value(swigCPtr, this));
  }

}
