/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class StdOptionalTextWeight {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StdOptionalTextWeight(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StdOptionalTextWeight obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StdOptionalTextWeight obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_StdOptionalTextWeight(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StdOptionalTextWeight() {
    this(AdaptiveCardObjectModelJNI.new_StdOptionalTextWeight__SWIG_0(), true);
  }

  public StdOptionalTextWeight(TextWeight arg0) {
    this(AdaptiveCardObjectModelJNI.new_StdOptionalTextWeight__SWIG_1(arg0.swigValue()), true);
  }

  public boolean has_value() {
    return AdaptiveCardObjectModelJNI.StdOptionalTextWeight_has_value(swigCPtr, this);
  }

  public TextWeight value() {
    return TextWeight.swigToEnum(AdaptiveCardObjectModelJNI.StdOptionalTextWeight_value(swigCPtr, this));
  }

}
