/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class StringResource {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected StringResource(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringResource obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_StringResource(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringResource() {
    this(AdaptiveCardObjectModelJNI.new_StringResource__SWIG_0(), true);
  }

  public StringResource(String defaultValue, SWIGTYPE_p_std__unordered_mapT_std__string_std__string_t localizedValues) {
    this(AdaptiveCardObjectModelJNI.new_StringResource__SWIG_1(defaultValue, SWIGTYPE_p_std__unordered_mapT_std__string_std__string_t.getCPtr(localizedValues)), true);
  }

  public boolean ShouldSerialize() {
    return AdaptiveCardObjectModelJNI.StringResource_ShouldSerialize(swigCPtr, this);
  }

  public String Serialize() {
    return AdaptiveCardObjectModelJNI.StringResource_Serialize(swigCPtr, this);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.StringResource_SerializeToJsonValue(swigCPtr, this), true);
  }

  public String GetDefaultValue() {
    return AdaptiveCardObjectModelJNI.StringResource_GetDefaultValue__SWIG_0(swigCPtr, this);
  }

  public String GetDefaultValue(String locale) {
    return AdaptiveCardObjectModelJNI.StringResource_GetDefaultValue__SWIG_1(swigCPtr, this, locale);
  }

  public SWIGTYPE_p_std__unordered_mapT_std__string_std__string_t GetLocalizedValue() {
    return new SWIGTYPE_p_std__unordered_mapT_std__string_std__string_t(AdaptiveCardObjectModelJNI.StringResource_GetLocalizedValue(swigCPtr, this), true);
  }

  public static StringResource Deserialize(ParseContext context, JsonValue json) {
    long cPtr = AdaptiveCardObjectModelJNI.StringResource_Deserialize(ParseContext.getCPtr(context), context, JsonValue.getCPtr(json), json);
    return (cPtr == 0) ? null : new StringResource(cPtr, true);
  }

  public static StringResource DeserializeFromString(ParseContext context, String jsonString) {
    long cPtr = AdaptiveCardObjectModelJNI.StringResource_DeserializeFromString(ParseContext.getCPtr(context), context, jsonString);
    return (cPtr == 0) ? null : new StringResource(cPtr, true);
  }

}
