/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public enum TargetWidthType {
  Default(0),
  VeryNarrow,
  Narrow,
  Standard,
  Wide,
  AtMostVeryNarrow,
  AtMostNarrow,
  AtMostStandard,
  AtMostWide,
  AtLeastVeryNarrow,
  AtLeastNarrow,
  AtLeastStandard,
  AtLeastWide;

  public final int swigValue() {
    return swigValue;
  }

  public static TargetWidthType swigToEnum(int swigValue) {
    TargetWidthType[] swigValues = TargetWidthType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (TargetWidthType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + TargetWidthType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private TargetWidthType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private TargetWidthType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private TargetWidthType(TargetWidthType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

