/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class TextBlockConfig {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TextBlockConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TextBlockConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(TextBlockConfig obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_TextBlockConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHeadingLevel(long value) {
    AdaptiveCardObjectModelJNI.TextBlockConfig_headingLevel_set(swigCPtr, this, value);
  }

  public long getHeadingLevel() {
    return AdaptiveCardObjectModelJNI.TextBlockConfig_headingLevel_get(swigCPtr, this);
  }

  public static TextBlockConfig Deserialize(JsonValue json, TextBlockConfig defaultValue) {
    return new TextBlockConfig(AdaptiveCardObjectModelJNI.TextBlockConfig_Deserialize(JsonValue.getCPtr(json), json, TextBlockConfig.getCPtr(defaultValue), defaultValue), true);
  }

  public TextBlockConfig() {
    this(AdaptiveCardObjectModelJNI.new_TextBlockConfig(), true);
  }

}
