/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class ThemedUrl {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected ThemedUrl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ThemedUrl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_ThemedUrl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ThemedUrl() {
    this(AdaptiveCardObjectModelJNI.new_ThemedUrl__SWIG_0(), true);
  }

  public ThemedUrl(ThemedUrl arg0) {
    this(AdaptiveCardObjectModelJNI.new_ThemedUrl__SWIG_1(ThemedUrl.getCPtr(arg0), arg0), true);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.ThemedUrl_SerializeToJsonValue(swigCPtr, this), true);
  }

  public static ThemedUrl Deserialize(ParseContext arg0, JsonValue json) {
    long cPtr = AdaptiveCardObjectModelJNI.ThemedUrl_Deserialize(ParseContext.getCPtr(arg0), arg0, JsonValue.getCPtr(json), json);
    return (cPtr == 0) ? null : new ThemedUrl(cPtr, true);
  }

  public ACTheme GetTheme() {
    return ACTheme.swigToEnum(AdaptiveCardObjectModelJNI.ThemedUrl_GetTheme(swigCPtr, this));
  }

  public String GetUrl() {
    return AdaptiveCardObjectModelJNI.ThemedUrl_GetUrl(swigCPtr, this);
  }

  public static String GetThemedUrl(ACTheme theme, SWIGTYPE_p_std__vectorT_std__shared_ptrT_AdaptiveCards__ThemedUrl_t_t themedUrls, String defaultIconUrl) {
    return AdaptiveCardObjectModelJNI.ThemedUrl_GetThemedUrl(theme.swigValue(), SWIGTYPE_p_std__vectorT_std__shared_ptrT_AdaptiveCards__ThemedUrl_t_t.getCPtr(themedUrls), defaultIconUrl);
  }

}
