/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public class ValueChangedAction {
  private transient long swigCPtr;
  private transient boolean swigCMemOwn;

  protected ValueChangedAction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ValueChangedAction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwn = own;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AdaptiveCardObjectModelJNI.delete_ValueChangedAction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ValueChangedAction() {
    this(AdaptiveCardObjectModelJNI.new_ValueChangedAction__SWIG_0(), true);
  }

  public ValueChangedAction(StringVector targetInputIds) {
    this(AdaptiveCardObjectModelJNI.new_ValueChangedAction__SWIG_1(StringVector.getCPtr(targetInputIds), targetInputIds), true);
  }

  public ValueChangedAction(StringVector targetInputIds, ValueChangedActionType type) {
    this(AdaptiveCardObjectModelJNI.new_ValueChangedAction__SWIG_2(StringVector.getCPtr(targetInputIds), targetInputIds, type.swigValue()), true);
  }

  public StringVector GetTargetInputIds() {
    return new StringVector(AdaptiveCardObjectModelJNI.ValueChangedAction_GetTargetInputIds(swigCPtr, this), false);
  }

  public void SetTargetInputIds(StringVector arg0) {
    AdaptiveCardObjectModelJNI.ValueChangedAction_SetTargetInputIds(swigCPtr, this, StringVector.getCPtr(arg0), arg0);
  }

  public ValueChangedActionType GetValueChangedActionType() {
    return ValueChangedActionType.swigToEnum(AdaptiveCardObjectModelJNI.ValueChangedAction_GetValueChangedActionType(swigCPtr, this));
  }

  public void SetValueChangedActionType(ValueChangedActionType value) {
    AdaptiveCardObjectModelJNI.ValueChangedAction_SetValueChangedActionType(swigCPtr, this, value.swigValue());
  }

  public boolean ShouldSerialize() {
    return AdaptiveCardObjectModelJNI.ValueChangedAction_ShouldSerialize(swigCPtr, this);
  }

  public String Serialize() {
    return AdaptiveCardObjectModelJNI.ValueChangedAction_Serialize(swigCPtr, this);
  }

  public JsonValue SerializeToJsonValue() {
    return new JsonValue(AdaptiveCardObjectModelJNI.ValueChangedAction_SerializeToJsonValue(swigCPtr, this), true);
  }

  public static ValueChangedAction Deserialize(JsonValue json) {
    long cPtr = AdaptiveCardObjectModelJNI.ValueChangedAction_Deserialize(JsonValue.getCPtr(json), json);
    return (cPtr == 0) ? null : new ValueChangedAction(cPtr, true);
  }

  public static ValueChangedAction DeserializeFromString(String jsonString) {
    long cPtr = AdaptiveCardObjectModelJNI.ValueChangedAction_DeserializeFromString(jsonString);
    return (cPtr == 0) ? null : new ValueChangedAction(cPtr, true);
  }

  public static ValueChangedAction dynamic_cast(BaseCardElement baseCardElement) {
    long cPtr = AdaptiveCardObjectModelJNI.ValueChangedAction_dynamic_cast(BaseCardElement.getCPtr(baseCardElement), baseCardElement);
    return (cPtr == 0) ? null : new ValueChangedAction(cPtr, true);
  }

}
