/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.adaptivecards.objectmodel;

public enum ValueChangedActionType {
  ResetInputs;

  public final int swigValue() {
    return swigValue;
  }

  public static ValueChangedActionType swigToEnum(int swigValue) {
    ValueChangedActionType[] swigValues = ValueChangedActionType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ValueChangedActionType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ValueChangedActionType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ValueChangedActionType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ValueChangedActionType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ValueChangedActionType(ValueChangedActionType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

