name: $(Year:yy).$(Month).$(DayOfMonth).$(rev:r)
pr: none
trigger: none
pool:
  name: Azure Pipelines
  vmImage: macos-latest
variables:
- group: AdaptiveCards-KVLink
steps:
- task: Xcode@5
  displayName: Xcode build
  inputs:
    configuration: Release
    scheme: AdaptiveCards-Universal
    sdk: iphoneos
    xcWorkspacePath: source/ios/AdaptiveCards/AdaptiveCards.xcworkspace
- task: Bash@3
  displayName: Push To cocoapods
  inputs:
    targetType: inline
    script: "cat ./source/ios/tools/AdaptiveCards.podspec\nif type brew >/dev/null 2>&1;\nthen \n   brew upgrade cocoapods >/dev/null 2>&1; \n   brew install cocoapods >/dev/null 2>&1; \nfi\n\npod trunk push  ./source/ios/tools/AdaptiveCards.podspec\n"
  env:
    COCOAPODS_TRUNK_TOKEN: $(cocoapod-trunk-token)
